### ISSUE TITLE
Spring session with redis can't logut

### ISSUE THREAD

**Issue by zjengjie** [spring-projects/spring-session#1035]
Use webflux and spring session with redis, when logout it still logged in. Config like this:
```java
    @Bean
    public SecurityWebFilterChain securitygWebFilterChain(ServerHttpSecurity http) {
        // @formatter:off
        return http.authorizeExchange()
                .anyExchange().authenticated()
                .and().formLogin()
                .and()
                .build();
        // @formatter:on
    }
```
the version is 2.0.2.RELEASE.
I open a [sample](https://github.com/zjengjie/SpringSessionLogoutIssue) project to produce this issue.

**Comment by zjengjie** [comment]
this would be fix on [DATAREDIS-791](https://jira.spring.io/browse/DATAREDIS-791)

**Comment by vpavic** [comment]
Thanks for the report @zjengjie. I've reproduced the problem.

So the issue with Spring Boot `2.0.0.RELEASE` (and Spring Data Redis `2.0.5.RELEASE`) is that logout doesn't actually appear to clear the security context from the session.

With Spring Boot `2.0.1.RELEASE` (and Spring Data Redis `2.0.6.RELEASE` which includes [DATAREDIS-791](https://jira.spring.io/browse/DATAREDIS-791)) things are actually worse, as retrieval of the session throws NPE.

**Comment by zjengjie** [comment]
The NPE is because when spring session remove a attribute, it just put a null value to the attribute, but this didn't really delete it. I made a PR #1045 to show you how I avoid it by now, perhaps you have better solution.

**Comment by vpavic** [comment]
Thanks for following up @zjengjie. Setting an attribute value to `null` is not the real problem here, since we have the same behavior in `RedisOperationsSessionRepository`.

The real issue lies in how we map the session on retrieval from Redis - using [`Collectors#toMap`](https://github.com/spring-projects/spring-session/blob/master/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/ReactiveRedisOperationsSessionRepository.java#L153) is the problematic bit, since it doesn't allow `null` values (see [this SO question](https://stackoverflow.com/questions/24630963/java-8-nullpointerexception-in-collectors-tomap)).
