### ISSUE TITLE
why remove  "HASH_MAP" pattern on spring boot 2.x

### ISSUE THREAD

**Issue by jayzch** [spring-projects/spring-session#1043]
on 1.5.x  we can choose the StoreType "HASH_MAP" pattern that we  wish to use to store the sessions     .But on 2.x .it was removed,why?

https://github.com/spring-projects/spring-boot/blob/v2.0.1.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/StoreType.java

https://github.com/spring-projects/spring-boot/blob/v1.5.11.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/StoreType.java

**Comment by vpavic** [comment]
As explained in the [reference documentation](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-mapsessionrepository), the use of `MapSessionRepository` with a `ConcurrentHashMap` is intended as a testing or convenience mechanism since there's no mechanism to purge expired sessions. For that reason we've removed no-args constructor from `MapSessionRepository` in Spring Session 2.0 so that the users are required to supply their own map implementation that handles purging of expired sessions, a optionally session event handling.

You might want to take a look at spring-projects/spring-boot#9683 for more background on this.

**Comment by vpavic** [comment]
Can you explain your use case for `MapSessionRepository` backed by `ConcurrentHashMap`? We don't recommend the use of this combination for production purposes, for reasons explained above - nothing purges the expired sessions which just stay in the map a consume memory, session events are not supported and clustering in not possible. Simply using servlet container's session management facilities might be a better suited for production purposes.

**Comment by MikeN123** [comment]
One of the reasons to use Spring Session with a map implementation would be to have some programmatic control over your session cookies - with the upcoming changes to the `SameSite` handling by Chrome that may be relevant.

If you just want to replace your container session-implementation with Spring Session for that reason, something that stores things in an in-memory map may be fine. I was quite suprised to find out Spring Session does not really support that, but think that implementing something using a caching library like [Caffeine](https://github.com/ben-manes/caffeine) should be trivial, including the session expiry.
