### ISSUE TITLE
Option for disabling transactions for JDBC

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#1046]
Since the cost of transactions can be expensive, please provide an option to disable them completely.

**Comment by cemo** [comment]
Dear @rwinch please reconsider this since it has major impact on our servers. :)

And I would be really glad if you can explain what is the benefit using transaction for sessions.

**Comment by vpavic** [comment]
> And I would be really glad if you can explain what is the benefit using transaction for sessions.

Operations performed by `JdbcOperationsSessionRepository` should be atomic. Otherwise there's a risk of leaving data store in inconsistent state in case of errors, as well as potential concurrency issues.

I'm open to adding option to disable transactions, if @rwinch agrees, for those who can live with risks listed above.

**Comment by cemo** [comment]
@vpavic  I may be missing something but which `query` do you think that requires transactional support. Since It seems all of them are atomic already to me. The only exceptional case would be batch updates for session attributes which are already addressed as a batch statement.

**Comment by vpavic** [comment]
`JdbcOperationsSessionRepository#save` operates on session table, and optionally session attributes table. These two should be atomic.

There's also the situation of `JdbcOperationsSessionRepository` operations being invoked within the existing transaction. To avoid our operations joining a bigger, and potentially longer lasting transaction, we use `PROPAGATION_REQUIRES_NEW`.

Again, see #464 for background.

**Comment by cemo** [comment]
Thanks for the clarification. These are the risks we can take since the impact is much more important.

**Comment by cemo** [comment]
@vpavic I think supporting either `Transactional` and `NonTransactionalRepository` at the same time can be easy too. A plain `NonTransactionalRepository` implementation and a `Transactional` decorator implementation sounds enough. What do you think?

**Comment by vpavic** [comment]
Implementing this shouldn't be too hard, if and when we to do it.

At the moment I'd prefer to handle this within the existing `JdbcOperationsSessionRepository` by providing an option to disable transactions. Non-transactional implementation with transactional decorator sounds more complex and would be a breaking change.

**Comment by cemo** [comment]
@rwinch This is severely affecting performance of our applications. Please revert or support non-transactional repository as well.

**Comment by vpavic** [comment]
@cemo There's nothing to _revert_ since transactions were a part of `JdbcOperationsSesssionRepository` from day one (and by day one I mean the first stable release that introduced JDBC support i.e. `1.2.0.RELEASE`).

Support for disabling transactions is not imminent since it would be a new feature, and as such is a `2.1` candidate.

**Comment by vpavic** [comment]
This is now resolved via de16c30 by adding a new `JdbcOperationsSessionRepository` constructor that takes only `JdbcOperations` and uses a no-op `TransactionOperations` implementation internally, and will be available in `2.1.0.M2` shortly.
