### ISSUE TITLE
Is there any way to clear spring session redis key while redis keyspace notification is not allowed enable?

### ISSUE THREAD

**Issue by Fireflyever** [spring-projects/spring-session#1103]
See releated: https://github.com/spring-projects/spring-session/issues/1017

I have met the same problem while using spring session with redis and I found the redis key: 
spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME* will not delete and with a hugu size....

The redis server I use is 4.0+ and I am told the keyspace notification is not allowed to enable due to some performance & security reasons...

So my questions is: Is there any way to clear the redis key (spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.*) after the session expired under the situation that the redis keyspace notifcation is disable?

Thanks,
Lei

**Comment by vpavic** [comment]
Spring Session uses `ConfigureNotifyKeyspaceEventsAction` to configure keyspace notifications, if security configuration of Redis server allows it. Note that since this is done during application startup, if Redis server was restarted afterwards, the keyspace notifications config will be lost, until the application has restarted as well.

Obviously this isn't ideal, so that's why preferably the keyspace notifications should be configured in `redis.conf`.

See the following related documentation:
- https://docs.spring.io/spring-session/docs/2.0.x/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent
- https://docs.spring.io/spring-data/redis/docs/2.0.x/reference/html/#redis.repositories.expirations
- https://redis.io/topics/notifications#configuration

Without the keyspace notifications available in any form, I'm afraid the only alternative is to provide some custom handling of the stale keys.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please comment back and we can re-open the issue.

**Comment by Meyy-DL** [comment]
Apologizes for re-using this closed thread. 

We have same exact issue where _expired_ `spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:xxxx` is not getting cleaned up because of our secured redis cluster setup. 

It would be great if you can suggest any workaround or is there any solution in the works already? 

Thanks!

**Comment by vpavic** [comment]
@Meyy-DL, did you read the documentation linked in [my comment](https://github.com/spring-projects/spring-session/issues/1103#issuecomment-411582154)? Everything's really covered there.
