### ISSUE TITLE
spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:admin   is not Expire ?

### ISSUE THREAD

**Issue by 18703876065** [spring-projects/spring-session#1118]
### like this

127.0.0.1:6379> SMEMBERS spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:admin
1) "\xac\xed\x00\x05t\x00$62f0018f-6079-4f64-80a1-645c9a9935e3"
2) "\xac\xed\x00\x05t\x00$666c3a74-8198-4f63-b74e-0c5ecbfff50b"

### MyCode：
            WebUtils.setSessionAttribute(request,FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME,user.getUserName());

**Comment by 18703876065** [comment]
1) "spring:session:sessions:expires:20726f9b-9742-4479-a5c3-ef9a06b13ab2"
2) "spring:session:expirations:1531380000000"
3) "spring:session:sessions:20726f9b-9742-4479-a5c3-ef9a06b13ab2"
4) "spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:admin"
127.0.0.1:6379> SMEMBERS spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:admin
1) "\xac\xed\x00\x05t\x00$62f0018f-6079-4f64-80a1-645c9a9935e3"
2) "\xac\xed\x00\x05t\x00$666c3a74-8198-4f63-b74e-0c5ecbfff50b"
3) "\xac\xed\x00\x05t\x00$20726f9b-9742-4479-a5c3-ef9a06b13ab2"

**Comment by 18703876065** [comment]
this is  not a problem

**Comment by pabloradomski** [comment]
I have the same issue: how do to prevent it from growing indefinitely?

**Comment by cuckoo3** [comment]
The reason why the index keep growing: https://github.com/spring-projects/spring-session/issues/1395
The session key is not removed from the index when calling the cleanupExpiredSessions() function

**Comment by cyb** [comment]
I have same issue.

**Comment by douxiaofeng99** [comment]
We have same issue in our production env, but we have different scenery. We use spring session with oauth2.0  as sso server  and another spring boot project as a resource server. if the user just login, the session principal key will be removed normally. if user logged, then get the access token and access the resource service, in the  long principal key set, there will be some session ids without any real session key and expire key in the redis.   then theses ids will never deleted because there are no timeout and expire.
![image](https://user-images.githubusercontent.com/16471638/74997954-5c606100-5492-11ea-9cfb-6c92823e2dec.png)
![image](https://user-images.githubusercontent.com/16471638/74997985-726e2180-5492-11ea-8b78-ead0292803fa.png)
At last, the long key will be never removed.
