### ISSUE TITLE
Document minimum requirements to use spring-session

### ISSUE THREAD

**Issue by dave-r12** [spring-projects/spring-session#119]
I'm looking to use spring session and I didn't see anything in the docs which outlines what dependencies are required and their versions. From the issues list, it looks like servlet 3.0+ is required. Would it be possible to expose this some of this in the docs?

**Comment by rwinch** [comment]
Thank you for the feedback.

Do you have any specific questions that I can answer now? I will be sure to include them in the documentation as well.

* Spring Session has a single required dependency (commons-logging).
* HttpSession Redis implementation requires
** Servlet 2.5 should be the minimum, but we have a bug #111 that will be fixed in 1.0.1
** Redis 2.8.0+ to support [keyspace notifications](http://redis.io/topics/notifications) See #115
** Spring Data Redis (it is known and tested to work with 1.3.0)
** redis.clients (it is known and tested to work with 2.4.1)
* WebSocket implementation requires spring-websocket-4.1.4

If you are looking for an easy way to manage your dependency versions, then I would suggest the [Spring IO Platform](http://docs.spring.io/platform/docs/1.1.1.RELEASE/reference/htmlsingle/) which provides known working versions of projects that work together along with easy mechanisms to manage the versions (i.e. using a [Maven BOM](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies)).

**Comment by dave-r12** [comment]
Excellent, thanks for the fast reply.

We are on spring framework 3.2, is there a minimum version there?

**Comment by rwinch** [comment]
If you are NOT using web sockets (i.e. only using HttpSession integration) then Spring 3.2.x *should work*  (we officially test against Spring 4.1.x). However, we should also add tests to confirm this (Created #120). Please let me know if you have any problems or not. If you do, we can certainly make some changes to ensure Spring 3.2.x works.
