### ISSUE TITLE
Improve configuration support for customizing JDBC session SQL statements

### ISSUE THREAD

**Issue by BenDol** [spring-projects/spring-session#1199]
I want to simply override the `prepareQueries` method in this repository class and add my overriden queries there. For some reason this is private for no obvious reason (perhaps I am missing it).

Would be like to make this method `protected`

```java
protected void prepareQueries() {
    this.createSessionQuery = getQuery(CREATE_SESSION_QUERY);
    this.createSessionAttributeQuery = getQuery(CREATE_SESSION_ATTRIBUTE_QUERY);
    this.getSessionQuery = getQuery(GET_SESSION_QUERY);
    this.updateSessionQuery = getQuery(UPDATE_SESSION_QUERY);
    this.updateSessionAttributeQuery = getQuery(UPDATE_SESSION_ATTRIBUTE_QUERY);
    this.deleteSessionAttributeQuery = getQuery(DELETE_SESSION_ATTRIBUTE_QUERY);
    this.deleteSessionQuery = getQuery(DELETE_SESSION_QUERY);
    this.listSessionsByPrincipalNameQuery =
            getQuery(LIST_SESSIONS_BY_PRINCIPAL_NAME_QUERY);
    this.deleteSessionsByExpiryTimeQuery =
            getQuery(DELETE_SESSIONS_BY_EXPIRY_TIME_QUERY);
}
```

Thanks!

**Comment by BenDol** [comment]
In fact is appears there isn't an easy way to serve my own custom `JdbcOperationsSessionRepository` implementation using the `SessionAutoConfiguration.class`. Would be nice if it allowed us to serve the sessionRepositoy to the `JdbcHttpSessionConfiguration` configuration.

Thoughts?

**Comment by vpavic** [comment]
The `JdbcOperationsSessionRepository` exposes a number of `#set*Query` methods that can be used to provide custom SQL queries. Why do you need to override `prepareQueries`?

Regarding Spring Boot and its `SessionAutoConfiguration`, the Servlet part is `@ConditionalOnMissingBean(SessionRepository.class)` which means if you provide a custom `SessionRepository` implementation as a `@Bean`, Spring Boot will back-off, which is reasonable.

**Comment by BenDol** [comment]
Yeah unfortunately I've just had to replicate `JdbcSessionConfiguration` and `JdbcHttpSessionConfiguration` and have it load before `SessionAutoConfiguration` with my `JdbcOperationsSessionRepository`. Because I still want all the default configurations that spring-session and spring-boot provides, I just wanted to server my own SessionRepository implementation to be used with the configurations.

**Comment by vpavic** [comment]
Yes, Spring Boot's auto-configuration will back-off once you provide a `SessionRepository` bean. Maybe we can look into providing some hook point in `JdbcHttpSessionConfiguration` that would allow the users to customize the SQL without manually registering `JdbcOperationsSessionRepository` bean.

**Comment by moleksyuk** [comment]
Hi @vpavic 
I've got similar problem with defining custom names for `SPRING_SESSION` & `SPRING_SESSION_ATTRIBUTES` tables.

I can override just table name for `SPRING_SESSION` by `org.springframework.session.jdbc.JdbcOperationsSessionRepository#setTableName`
BUT for I would like to have `org.springframework.session.jdbc.JdbcOperationsSessionRepository#setSessionAttributeTableName`
because I would like to define tables with the same naming convention as it already exists in my schema (all tables in lower case) but will get:
`session` - aka `SPRING_SESSION`
`session_ATTRIBUTES` - aka `SPRING_SESSION_ATTRIBUTES`
which look strange 😞

**Comment by vpavic** [comment]
Hi @moleksyuk - as your request is a bit different, could you please open a new issue?

**Comment by vpavic** [comment]
Instead of going with configuration API that's focused on `JdbcOperationsSessionRepository` and configuring custom SQL, we've decided to go in a bit more generic direction and provide session repository customizers - see #1499.

That will allow to apply more advanced configuration without have to register the session repository bean manually, and therefore have Spring Boot's auto-configuration back off.

**Comment by pmgkrishna** [comment]
@vpavic can you share any spring document to provide a jdbcOperationsSessionRepository?
