### ISSUE TITLE
Consider providing embedded redis server

### ISSUE THREAD

**Issue by dave-r12** [spring-projects/spring-session#121]
While configuring one of our apps to use spring-session, I noticed in the samples directory there was a class for creating an embedded redis server (https://github.com/spring-projects/spring-session/blob/master/samples/httpsession/src/main/java/sample/EmbeddedRedisConfiguration.java). I was thinking in our dev environment, we would use this approach.

I copy/pasted the sample for now, but thought this might be helpful in general to others using spring-session.

**Comment by xenoterracide** [comment]
agreed, this is probably something done in a starter? this class is mentioned in the documentation like it's something you don't write...

**Comment by rwinch** [comment]
I do think that providing an embedded Redis solution would be very useful. However, I'm thinking it may be better to do this in Spring Data Redis since it is generally more applicable than Spring Session.

Thoughts @olivergierke ?

**Comment by domdorn** [comment]
I think that's fixed.

**Comment by rwinch** [comment]
*bump* @olivergierke

**Comment by olivergierke** [comment]
For Redis, @thomasdarimont should be able to give more insight.

**Comment by thomasdarimont** [comment]
We already looked at this before but at that time the used Redis version was pretty old. Looks better now, I filed: https://jira.spring.io/browse/DATAREDIS-376 and https://github.com/kstyrc/embedded-redis/issues/30

**Comment by rwinch** [comment]
@thomasdarimont Thanks for the response. Do you consider kstyrc/embedded-redis#30 a show stopper for including support in Spring Data Redis? I think we could enhance the Spring Data support to use a specific version later on. Thoughts?

**Comment by rwinch** [comment]
Thanks for the request. I would really have liked to supported this feature. Unfortunately supporting embedded Redis seems quite impractical at this point. The problems are many (#247 #232 #216 #150 kstyrc/embedded-redis/issues/40) . In summary:

* We cannot provide binaries for Linux distributions that will work across the board (#247)
* Windows support is still broken

For these reasons, we are no longer supporting running embedded redis. Since the jar was never published (and just in the samples) this is not a passivity concern.
