### ISSUE TITLE
Add ability to get all logged in principals

### ISSUE THREAD

**Issue by spazbob** [spring-projects/spring-session#1269]
It would be really useful to have an operation that returns a list of principals that currently have an authenticated session active.

Essentially, I'm looking for something that is the equivalent of this SQL:

SELECT principal_name FROM spring_session WHERE principal_name IS NOT NULL;

I'm interested in this for the JDBC support, and could potentially provide a PR for this. But if it would require implementing for all the other repositories, probably not.

**Comment by rwinch** [comment]
I think it would be alright to put this on specific implementations (perhaps leveraging existing Spring Data interfaces if one wanted an interface), but I don't think we would ever add this to the interface as that is driven by what Spring Session needs to operate. We would need to keep in mind that paging (thus sorting) would be required as there may be too many sessions to load into memory.

What are your thoughts @vpavic?

**Comment by vpavic** [comment]
I agree that this isn't likely to be added to Spring Session's API, such as `FindByIndexNameSessionRepository`, due to the technical limitations of some data stores. See #255 which is somewhat related to this.

Regarding `JdbcOperationsSessionRepository` specific implementation, I'm not in favor of that either. I wouldn't want to bring Spring Data into to mix as it feels like an overhead to the core functionality that `JdbcOperationsSessionRepository` provides. I'm also not a fan of `offset` pagination, as it's broken by design IMO (see [this article](https://use-the-index-luke.com/no-offset)) due to both performance considerations and result anomalies, which are more obvious with dynamic data, such as sessions.

Looking at the originally requested query (`SELECT principal_name FROM spring_session WHERE principal_name IS NOT NULL`), that should be fairly simple to address in the custom code.

**Comment by spazbob** [comment]
Hi @vpavic @rwinch - are you waiting further feedback from me on this? Or are you comments the go-ahead for me to provide a PR?

**Comment by vpavic** [comment]
Thanks for following up @spazbob - I was mainly looking for the feedback on remark that I find it as something that should be fairly simple to address in the custom code.

For the reasons outlined in my previous comment, I'm not keen on adding this out-of-the-box.
