### ISSUE TITLE
RequestContextListener with Spring Session

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#129]
We need to access some session bean scope beans but this is causing an error in our side. Since `org.springframework.web.context.request.RequestContextListener` is setting `Request` very early, Accessing a SessionScope bean is throwing an exception. `org.springframework.web.context.request.RequestContextHolder` must be set after wrapping Request by SessionRepository. 

Using `org.springframework.web.filter.RequestContextFilter` instead of `org.springframework.web.context.request.RequestContextListener` is a solution but this is not common practice. For example even Spring Boot is using [RequestContextListener](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration.java#L179).   

It seems that RequestContextListener should not be used with Spring Session. What do you think?

**Comment by rwinch** [comment]
Thanks for the report.

As you pointed out, at this time there is no integration with Spring Session and ServletRequestListener which means it is essentially a no go with Spring Session.

Are their any particular reasons Spring Boot uses the RequestContextListener @philwebb or is this something that could be changed to use the RequestContextFilter?

One possible option for supporting something like this is to ensure you decorate the ServletRequestListener instead of using the ServletRequestListener directly. For example:

```java
public class RequestContextListener implements ServletRequestListener {
    private ServletRequestListener delegate;

    public void requestInitialized(ServletRequestEvent requestEvent) {
        delegate.requestInitialized(wrap(requestEvent));
    }

    public void requestDestroyed(ServletRequestEvent requestEvent) {
        delegate.requestDestroyed(wrap(requestEvent);
    }

    private ServletRequestEvent wrap(ServletRequestEvent e) {
        return new ServletRequestEvent(e.getServletContext(), wrap(e.getServletRequest());
    }

    private ServletRequest wrap(ServletRequest r) {
        return new SessionRepositoryRequestWrapper(...);
    }
}
``` 

The problem right now is that `SessionRepositoryRequestWrapper` is private so would not work. 

I'm not sure if I really like this as an option since it seems like we should be able to use a Filter which already works. I guess it probably depends on what @philwebb replies with.

**Comment by philwebb** [comment]
@rwinch We'd have to do some testing if we switched from `RequestContextListener` to `RequestContextFilter` and it probably couldn't happen until 1.3. I'm not aware of any specific reason why we chose one over the other.

**Comment by cemo** [comment]
Having both `RequestContextListener` and `RequestContextFilter`together seems harmless at first glance. Maybe in case a existing `Spring Session Filter` and `ContextListener` beans,  RequestContextFilter can be registered as well.

**Comment by cemo** [comment]
@philwebb, @rwinch Is there anything I can provide for this issue? There is not any issue for this in Spring Boot yet.

**Comment by philwebb** [comment]
@cemo A Spring Boot issue would be appreciated. We could take a look for 1.3

**Comment by arcseldon** [comment]
Hi, can anyone please provide an update on this please?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
