### ISSUE TITLE
LettuceConnectionFactory is not taking hostname and  port number from application.yml

### ISSUE THREAD

**Issue by jobinvjohn** [spring-projects/spring-session#1302]
Hi,
When i try to use spring session in spring cloud gateway, noticed that port number and host name is not picking up from application.yml and instead it is always connecting to localhost redis. When I pass it as Constructor arguments for LettuceConnectionFactory it works.

**Comment by vpavic** [comment]
Thanks for the report @jobinvjohn - this sounds like a configuration problem, and one that's not actually related to Spring Session itself. Can you share a minimal sample that can be used to reproduce this problem?

**Comment by jobinvjohn** [comment]
Please find the sample app.
[gateway-session-demo.zip](https://github.com/spring-projects/spring-session/files/2716611/gateway-session-demo.zip)

**Comment by vpavic** [comment]
Thanks for the sample @jobinvjohn - I'm afraid this is a configuration problem on your side, and actually one more related to Spring Boot rather than Spring Session.

There's no need to manually create the `LettuceConnectionFactory` and no use from injecting values from application properties using `@Value`. Simply remove everything except the declaration of `HttpSessionIdResolver` bean from your `SessionConfig` class and that'll yield the result that you seek. You can also remove `@EnableRedisWebSession` annotation.

Consider taking a closer look at Spring Boot's [reference manual](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/) to learn about auto-configuration capabilities. With that, I'm closing this as invalid.
