### ISSUE TITLE
Spring Session migration from 1.3.3 to 2.x doesn't migrate table schemas 

### ISSUE THREAD

**Issue by NickyMateev** [spring-projects/spring-session#1307]
I am in the process of migrating a Spring Boot project from 1.X to 2.X.
The project has a dependency to Spring Session:

```
<dependency>
    <groupId>org.springframework.session</groupId>
     <artifactId>spring-session-jdbc</artifactId>
</dependency>
```

Before migrating the project the working version of the `spring-session-jdbc` dependency was **1.3.3**.

After migration, the version of `spring-session-jdbc` is now **2.0.8**.

Upon starting my project I immediately start getting periodic exceptions of the sort: *"column "expiry_time" does not exist"* (from an async job that tries to clean up expired sessions)

It seems like there are some schema changes in the session tables that have occurred between the period of my old version and the current new one. After observing the database I can see that the new columns have not been added (columns such as **expiry_time** and **session_id**).

The only workaround I've found is to drop the two session tables (**spring_session** and **spring_session_attributes**) manually and let Spring Session create new ones (with the new columns).

This is very inconvenient and can be a non-trivial task for production environments. Does **Spring Session** really not have any migration capabilities?

**Comment by vpavic** [comment]
In Spring Session 2.0 our JDBC integration did make some breaking changes to database schema, in order to support the change session id functionality.

Regarding schema migration capabilities, we don't provide those OOTB as that's not a trivial problem to solve and is best handled at application level using tools like Liquibase or Flyway. Note that Spring Session itself doesn't initially create the tables either - that's a feature of Spring Boot's auto-configuration support for Spring Session.

Your options are to either manually migrate the sessions - note that this might not be that easy if you're using Spring Security (and upgrading it as well) and storing `SecurityContext` in the session as they are by design not intended to be serializable between different major versions.

Other option is to drop the old tables and create new ones - the challenge here is to plan the production roll-out in such manner that as few users as possible are affected. This can be difficult with session configured with bigger `maxInactiveInterval`.

With that, I'm closing this as answered.

**Comment by NickyMateev** [comment]
Got it. @vpavic thanks for the response!
