### ISSUE TITLE
How can I update another user's session

### ISSUE THREAD

**Issue by pain301** [spring-projects/spring-session#1407]
In my system, every user has a attribute: `deptCode`, which is session level attribute. When the user login, the `deptCode` is set by user or initialized by system. But, if admin remove the user from department, I also need to update the `deptCode` to null. So, how can I get the session of another user and update it

```java
// org.springframework.security.core.userdetails.User
public class CurrentUser extends User {
  private String name;
  private String deptCode;
}
```

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Briefly, you can retrieve the user's session by username. See this [guide and sample](https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-findbyusername.html) for more details.
