### ISSUE TITLE
Spring Session - Spring Security with Hazelcast

### ISSUE THREAD

**Issue by ernakulgoyal** [spring-projects/spring-session#1434]
Hello there,

Sorry to raise an issue here, but its really important for me to get this resolved.

I am trying to configure spring session using Hazelcast with spring security concurrency control, for the use case I want only one user session at a time across multiple devices.

I followed the guide the exact same way its mentioned: https://docs.spring.io/spring-session/docs/current/reference/html5/guides/java-hazelcast.html

**Issue I am facing is every time I am getting empty session repository.**

I am using : 
**hazelcast 3.11.4, 
spring-session-hazelcast 2.1.6.RELEASE, 
spring-boot-starter-security/web 2.0.4.RELEASE**

I am attaching my security config here: 
[SecurityConfig.txt](https://github.com/spring-projects/spring-session/files/3212216/SecurityConfig.txt)

I am not sure what the issue is but unable to find any content or samples related to the configurations I am using.

Can someone help? May be if someone could share a sample which uses custom concurrency control.

Thanks in advance!

**Comment by vpavic** [comment]
Hi @ernakulgoyal - looking at the `SecurityConfig` you attached, the problem is that you're using Spring Security's standard `SessionRegistry` implementation i.e. `SessionRegistryImpl`. This implementation is not aware of Spring Session's store.

Take a look at [_Spring Security Concurrent Session Control_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#spring-security-concurrent-sessions) of our reference manual. In short, you should use Spring Session's `SpringSessionBackedSessionRegistry` here.

Does that help?

**Comment by ernakulgoyal** [comment]
Hi @vpavic, thanks for replying to this thread.
Its working fine now.

Also, just a quick question, is there any way to get all the principals/custom user entities of logged in users (since 'getAllPrincipals' can not be used)?

**Comment by vpavic** [comment]
Thanks for following up @ernakulgoyal, glad to hear you got it to work.

Regarding the question on retrieving all the principals, there's no such API in Spring Session as that concern is highly dependent on the capabilities of the data store that's used to store sessions. So that's something that would require custom implementation.
