### ISSUE TITLE
RedisOperationsSessionRepository How to save

### ISSUE THREAD

**Issue by antusen** [spring-projects/spring-session#1479]
@Autowired
private RedisOperationsSessionRepository redisOperationsSessionRepository;

redisOperationsSessionRepository.save((RedisOperationsSessionRepository.RedisSession) session);
### Is this feasible?
((SessionRepository) redisOperationsSessionRepository).save(session);

**Comment by rwinch** [comment]
Is there a reason you are using Spring Session directly vs using the HttpSession? [Using HttpSession APIs is preferred](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-sessionrepository) but you can use it [directly if needed](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-session).

Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
