### ISSUE TITLE
Add GemFire Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#148]
There has been [some](https://spring.io/blog/2014/07/08/spring-session-1-0-0-m1-released#comment-1853090512) interest in GemFire base repository. A partial solution exists on [github](https://github.com/viniciusccarvalho/spring-session-data-gemfire)

**Comment by tcesenthil** [comment]
After reading through the Spring Session Documentation, here is my understanding. Will these 3 steps (at a high level) be sufficient to allow Spring Session to write to Gemfire repository instead of Redis ? I am interested in getting this component developed and tested for public & my private use.

Step 1: Implement just a Configuration class which provide all functions as the annotation

 1. Allow spring to Load the configuration class 
 2. Register Spring Session Filter in Container 
 3. Establish Repo Connection Factory
 4. Repo connection configuration

we will continue to re-use the Spring Session’s springSessionRepositoryFilter

Step 2: Need to develop an equivalent GemfireOperationsSessionRepository implementing the interface SessionRepository<S Session>

Step 3: SessionMessageListener.java 
   3.1. Need to decide a technique to identify and save delta changes in Session to underlying repository
   3.2. Need to see how session expire notification from underlying repository can be captured to invoke SessionDestroyEvent and cleanup operations -
