### ISSUE TITLE
How to use Spring Session and Spring Security OAuth2 together?

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-projects/spring-session#149]
Hi - I'd like to understand the relationship between spring session an spring security oauth2. Moreover, how does one go about integrating the two? Thanks in advance for you help/guidance.

**Comment by elewyeen** [comment]
@ EnableResourceServer conflict with @ EnableRedisHttpSession.
Looks like Fiter order caused by the conflict. 
Someone tried?

**Comment by xiaolongyuan** [comment]
+1

**Comment by rwinch** [comment]
This should work out of the box once #395 is resolved. Did you have any specific questions/problems?

**Comment by PedroAlvarado** [comment]
@rwinch I'm ignorant as to what would be the roles and benefits of using spring session in combination with spring oauth2 from an architectural perspective, specially in the context of a spring cloud application?

**Comment by rwinch** [comment]
@PedroAlvarado Like many forms of authentication it is about exchanging one set of credentials for another. Perhaps an application supports multiple forms of authentication (i.e. OAuth, SAML, username / password, etc). It might make sense to have an endpoint that exchanges these credentials for a session token. This will ensure that the rest of the application is relying only on a single type of authentication.

You might ask...why use session vs SAML, OAuth, etc? The answer is because a session id is simple (just a string based comparison) and quite secure (it is short lived, secure random generated, etc). Furthermore, it is one of the only long lasting credentials that has really "survived" throughout the years. 

OAuth (and many other authentication types) are still quite young. If you look at OAuth2 and a session id the two are actually quite similar. Both are a barer tokens (if you have the token, then you are treated as authenticated). The difference is really that OAuth presents a few common ways of obtaining and providing the token. 

What makes things more fragile is when developers try to use cryptography (i.e. JWT) instead of a data store. Cryptography is quite complicated and should be avoided if there are simpler ways to keep things secure (i.e. secure random generated token and a data store).

**Comment by vksjoshi** [comment]
Hi,

Can you please provide some sample project for spring session and spring security oauth2 together?

**Comment by eduyayo** [comment]
I've got to secure a REST API with client access and client customers access. So I've got kind-of the same problem here. 
I serve OAuth2 tokens to our B2B Clients but I still need and have to keep the preauthentication and such.
Right now I'm clueless on how to relate both: companyX has a userY who will, somehow, use the rest services as a final user (end user) and not as B2B. Or that's what my boss wants.

I was thinking on a mandatory register action for final users through an oauth2 endpoint and tell the companyX to post registrations there.

anyone with such a case?? need ideas desperately :/

**Comment by ptahchiev** [comment]
I have few questions here. Given this code: 
```
        // @formatter:off
        ResultActions result = getMockMvc().perform(
                        post("/oauth/token")
                        .params(params)
                        .with(httpBasic("test", "test-passwd"))
                        .accept(MediaType.APPLICATION_JSON_UTF8_VALUE)
                        .contentType(MediaType.APPLICATION_JSON_UTF8_VALUE))
                        .andDo(print())
                        .andDo(document("facade/authenticate"))
                        .andExpect(status().isOk())
                        .andExpect(content().contentType(MediaType.APPLICATION_JSON_UTF8_VALUE))
                        .andExpect(content().string(Is.is(not(nullValue()))));

        // @formatter:on

        final String resultString = result.andReturn().getResponse().getContentAsString();

        final JacksonJsonParser jsonParser = new JacksonJsonParser();

        final String token = jsonParser.parseMap(resultString).get("access_token").toString();
```
1) The token that is returned is not the session id. Correct?
2) If we invoke the server like this:
```
        getMockMvc().perform(post("/facade/i18n/locale/current").header(HttpHeaders.AUTHORIZATION, "Bearer " + token).param("locale", "bg").accept(
                        MEDIA_TYPE).contentType(MEDIA_TYPE)).andDo(print()).andDo(document("facade/" + I18NFacade.NAME + "/setCurrentLocale")).andExpect(
                        status().isOk());
```
and specify the `Authorization` bearer how will spring-session know which session is the correct based on the token?
3) If I specify a custom `HeaderHttpSessionStrategy` with the:
```
        HeaderHttpSessionStrategy headerHttpSessionStrategy = new HeaderHttpSessionStrategy();
        headerHttpSessionStrategy.setHeaderName(HttpHeaders.AUTHORIZATION);
```
then spring-session will use the token in the header to find the correct session but because the sessionID and the token are totally different it will not be able to find it. Correct?
4) It turns out I will need to implement custom `HttpSessionStrategy` that based on the token in the database finds the correct session. Correct? Is there such a thing already somewhere in spring-session or spring-security-oauth2?

**Comment by vpavic** [comment]
> The token that is returned is not the session id. Correct?

From the snippet you've provided I can assume that the URI you're invoking (`/oauth/token`) is the Authorization Server's Token Endpoint so the returned token is the OAuth Access Token, not the session id (note that the Token Endpoint is a stateless API invoked by client apps, not end users).

> If we invoke the server like this [_code snippet removed_] and specify the `Authorization` bearer how will spring-session know which session is the correct based on the token?

This really depends on what's the role of `/facade/i18n/locale/current` - is it a resource on the client app or is it some sort of Resource Server API? I see you're providing an access token in the Authorization header which would suggest that it's Resource Server's API - that should be a stateless API so I don't understand why you have session in the mix?

> If I specify a custom `HeaderHttpSessionStrategy` with the: [_code snippet removed_] then spring-session will use the token in the header to find the correct session but because the sessionID and the token are totally different it will not be able to find it. Correct?

Correct.

> It turns out I will need to implement custom `HttpSessionStrategy` that based on the token in the database finds the correct session. Correct? Is there such a thing already somewhere in spring-session or spring-security-oauth2? Or perhaps it would be easier to create an OAuth `TokenStore` implementation from the spring-session's `SessionRepository`?

Like with question no. 2, it depends on what are the OAuth roles of components in your system. It seems to me that you're mixing the client and Resource Server concerns.

Can you provide a more detailed description of the system overall, or ideally, a simplified sample(s) that demonstrate your setup?

**Comment by vpavic** [comment]
I'd also like to add a note that introducing Spring Session to the mix shouldn't really have a fundamental influence on the use of OAuth2 within your project. That is, since Spring Session typically operates behind a standard API (which is the `HttpSession`) by simply enhancing the session store and providing advanced options for correlating session to requests, it is somewhat assumed that you're already using the `HttpSession`.

Within the context of OAuth2, we can break things up according to the component you're implementing:
- Client app: it's likely that server based OAuth2 Client app already uses `HttpSession` and therefore it makes sense to use Spring Session and benefit from all the goodies it brings
- Resource Server app: since this component provides a stateless API that's authenticated against using an Access Token as a bearer, the `HttpSession` is not used and therefore Spring Session isn't suitable as well
- Authorization Server app: it's highly likely that this already uses `HttpSession` so similarly like with  OAuth2 Client app, it makes sense to use Spring Session and benefit from all the goodies it brings

Of course, there's always a possibility of mixing either of the above withing the same app, however this brings some complexity that need to be addressed with care (multiple security configs) but the general guidelines still apply.

With that, I'm closing this as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
