### ISSUE TITLE
Provide a way to extend jdbc session

### ISSUE THREAD

**Issue by okohub** [spring-projects/spring-session#1493]
Nowadays, a session with minimal info, I mean just principal and time fields, is not meeting real world requirements. More metadata and queryable fields should be included with session, like IP of request that creates session, or device information of last access in session.

Jdbc repository and session structure are very strict. I think they should be extendable and configurable. Actually I'm not sure about technic which would fit this, Maybe spring-data-jdbc project is elegant for this kind of solution. I just want to discuss this :)

Thanks.

**Comment by vpavic** [comment]
> More metadata and queryable fields should be included with session, like IP of request that creates session, or device information of last access in session.

This sounds like you are interested in custom indexes on your sessions.

You might be aware that we've recently introduced `IndexResolver` in #557. Granted, it's not quite exposed to users at the moment, but we're looking at improving that in #1467. That would allow you to register resolver for your custom indexes, and at that point the only missing thing is how to write those indexes.

Alternatively, you could explore a custom `SessionRepository` implementation that uses stored routines. Both from performance and flexibility perspective this would be optimal since you'd be able to fully utilize your RDBMS.

**Comment by okohub** [comment]
@vpavic thank you for your response.

I also followed this: 

https://github.com/spring-projects/spring-session/pull/1481

And I totally understand your concerns in spring-session.
