### ISSUE TITLE
Use 'HeaderHttpSessionIdResolver' will create many new session of 'static request'

### ISSUE THREAD

**Issue by topsoft-support** [spring-projects/spring-session#1501]
`Spring-Session 2.x`
I use the Springboot project, using `@EnableRedisHttpSession`and `HeaderHttpSessionIdResolver`, the web is react dist file, and the dist file is deployed under Springboot resources/web ,with `spring.resources.static-locations = classpath:/ web/`.
SSO work fine!

```java
@EnableRedisHttpSession
@EnableConfigurationProperties(SessionProperties.class)
@Import(SessionProperties.class)
@Configuration
public class SessionConfiguration {

    @Resource(type = SessionProperties.class)
    private SessionProperties properties;

    @Bean
    public HttpSessionIdResolver httpSessionIdResolver() {
        return new HttpSessionidResolver(properties.getHeaderName());
    }
}
```

![image](https://user-images.githubusercontent.com/53323942/64336444-8a9ad300-d00f-11e9-877a-a95e6a3aec8a.png)

**The problem is :**
I found that every time I refresh the page, The spring-session will store many sessionids in redis. Debug code found that because the static file of the request did not add the sessionid of in header, thus creating a new session, Ajax request that I add the header and the session sharing is no problem. I don't want to refresh the page and create new sessions that cause redis to have a lot of useless data.

What is a good solution?

![image](https://user-images.githubusercontent.com/53323942/64337483-101f8280-d012-11e9-9f6d-4f7ff6a6d0d3.png)

Please help me . Thanks very much!!!

**Comment by vpavic** [comment]
@topsoft-support Is there any reason you're not using the default `CookieHttpSessionIdResolver`? That would ensure the session id is passed to the server on each request using cookie.

Alternatively, if you're sticking with `HeaderHttpSessionIdResolver` you either need to ensure your web client adds HTTP header with session id for all requests, or that you exclude your static resources from Spring Security config so that request to those resources doesn't initiate the session creation.

Having said that, this seems like a general usage question, would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that
other people can find it) or add some more details if you feel this is a genuine bug.
