### ISSUE TITLE
Session change doesn't remove old session

### ISSUE THREAD

**Issue by finke-ba** [spring-projects/spring-session#1519]
Hello @vpavic.

`SpringSessionWebSessionStore` in method `changeSessionId()` only change session id, but doesn't remove old one.
```
public Mono<Void> changeSessionId() {
	return Mono.defer(() -> {
		this.session
				.changeSessionId();
		return save();
	});
}
```
But in default implementation of `SessionStore` - `InMemoryWebSessionStore` it delete current one first and create new after that:
```
public Mono<Void> changeSessionId() {
	String currentId = this.id.get();
	InMemoryWebSessionStore.this.sessions.remove(currentId);
	String newId = String.valueOf(idGenerator.generateId());
	this.id.set(newId);
	InMemoryWebSessionStore.this.sessions.put(this.getId(), this);
	return Mono.empty();
}
```
Was it implemented without deleting old session by purpose and what is the correct way of removing old session in this case?

**Comment by vpavic** [comment]
Hi @finke-ba, thanks for reaching out.

Conceptually, Spring WebFlux's `InMemoryWebSessionStore` and Spring Session's `SpringSessionWebSessionStore` are quite different, because in case of default WebFlux implementation everything's in-memory and there's no concept of session repository like in Spring Session's implementation. When you actually do `WebSession#changeSessionId` on a `WebSession` that's backed by Spring Session's `ReactiveSessionRepository` it's actually repository's responsibility to take care of the removal, as that part is coupled to the concrete data store we're dealing with and its capabilities.

Are you experiencing any concrete problem with this?

**Comment by finke-ba** [comment]
@vpavic, thank you for the response.
My main problem that in my WebFlux application after logout I still have old session in DB and it's still possible to use this session. I mean if you save session cookie, logout and after that make a request with old cookie you will get previous session from db.
And I ended up in `WebSession#changeSessionId` which just create new session, but old session still exist and valid. I thought old session should be deleted or invalidated by default, without adding my custom logic somewhere. And as

**Comment by vpavic** [comment]
What's the actually `ReactiveSessionRepository` implementation you're using? Right now we have no information at all about your Spring Session setup. Can you provide a sample application that demonstrates the problem?

**Comment by finke-ba** [comment]
I'm using `ReactiveMongoOperationsSessionRepository`. Yes, I could provide example , but it will take some time to make it.

**Comment by vpavic** [comment]
MongoDB implementation is handled by separate project - you should open an issue against [spring-session-data-mongodb](https://github.com/spring-projects/spring-session-data-mongodb) repo. Once you do that, feel free to post a link to that issue here.

I'm going to close this for now, if it turns out this is a problem in Spring Session core, we can always reopen the issue later on.

**Comment by finke-ba** [comment]
@vpavic  could you tell me please why `WebSession#changeSessionId` it's not implemented like this:
```
@Override
public Mono<Void> changeSessionId() {
	return Mono.defer(() -> {
		this.session.changeSessionId();
		return invalidate().then(save());
	});
}
```

**Comment by finke-ba** [comment]
@vpavic please check this example - https://github.com/finke-ba/webflux-logout-not-delete-session-example

**Comment by vpavic** [comment]
As explained in [previous comment](#issuecomment-538020187), this is a responsibility of `ReactiveSessionRepository` that `SpringSessionWebSessionStore` delegates to.

For example, in Redis implementation this project provides, this is handled by Redis [`rename` command](https://redis.io/commands/rename):
https://github.com/spring-projects/spring-session/blob/e2abe36fa8bc28b5ee094bb421a6a5b61db4f9e2/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/ReactiveRedisSessionRepository.java#L305-L306

So the problem really is in MongoDB implementation, and should be reported in the appropriate project.

**Comment by finke-ba** [comment]
Okey, thank you for you help a lot! 
I'll report this issue to [spring-session-data-mongodb](https://github.com/spring-projects/spring-session-data-mongodb).
