### ISSUE TITLE
Allow overriding of cookie path and/or cookiePathGenerationStrategy in CookieHttpSessionStrategy

### ISSUE THREAD

**Issue by domdorn** [spring-projects/spring-session#155]
Allow to set the cookie path to a fixed value and/or allow to override the strategy on how to derive the cookie path.

**Comment by sreekanthsnair** [comment]
This is of very important, at least it should respect what web.xml config value of cookie-config path value

**Comment by sreekanthsnair** [comment]
@rwinch  any kind update on this, only because of this issue i'm stuck integrating spring session. We have an EAR project where we are setting all cookie path to / via web.xl to make our SSO work but due to spring session overriding cookie behaviors we are unable to proceed with spring session integration.

**Comment by rwinch** [comment]
@sreekanthsnair This will likely be scheduled for a 1.1. For now you can implement a modified version of [CookieHttpSessionStrategy](https://github.com/spring-projects/spring-session/blob/2d8664d84119d663a525ca6f0b2d86cd60cd09f4/spring-session/src/main/java/org/springframework/session/web/http/CookieHttpSessionStrategy.java) and provide it as a Bean.

**Comment by egov-systems** [comment]
@rwinch thanks,  you mean to say our own implementation of CookieHttpSessionStrategy  and provide it as bean or do spring-session is having any patch for the same ?

**Comment by rwinch** [comment]
@egov-systems For now those that need to set the cookie path can implement HttpSessionManager themselves. The implementation will look strikingly similar to CookieHttpSessionStrategy, but with the ability to set the cookie path. You will then need to provide it as a Bean.

In a future version of Spring Session (quite likely 1.1) we will provide this functionality out of the box and you can delete your custom implementation and leverage the built in support.

**Comment by egov-systems** [comment]
@rwinch thanks Rob

**Comment by domdorn** [comment]
hmm... just out of curiosity... something wrong with my patch? I'm fine with adjusting/enhancing it.

**Comment by rwinch** [comment]
@domdorn To be honest, I just haven't had a lot of time to look at it. In order to avoid too much context switching, I typically work for a set period of time on one project. Then work for a set time on another, until I rotate through the projects I work on.

I will be focussing on a patch release for Spring Session within the next week. To be honest, I probably need to figure out a better system on how I manage open source contributions, but I haven't found a better system yet (suggestions welcome :) ).

In terms of why it is scheduled for 1.1 vs 1.0.1 we try to be pretty strict on including only bug fixes in patch releases to ensure that upgrades go as smoothly as possible. You can learn more about the versioning here https://apr.apache.org/versioning.html

**Comment by sreekanthsnair** [comment]
@rwinch I possibly see a serious(in some degree) when we implement a modified version of CookieHttpSessionStrategy  with cookie override path as "/", this is leading to all war shares a single session. Can you please tell me, this is how spring-session designed behaves ? Does spring-session fetching stored session back using cookie value (like path)?

**Comment by sreekanthsnair** [comment]
One more question when we integrate spring-session along with spring-security do we have to configure anything specific?, since spring's SecurityContextHolder always returning valid Authentication for all war, even if i just logged into one war.

**Comment by rwinch** [comment]
Thanks for the great request! I'm trying to aggregate all the feature requests for cookies, so we can solve this problem more holistically. Therefore, I'm closing this in favor of #299 which takes this feature into account.

**Comment by rwinch** [comment]
This is now resolved via #299 See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html for details.

**Comment by sreekanthsnair** [comment]
@rwinch Wonderful... thanks and shall we expect the final release soon ?

**Comment by rwinch** [comment]
A milestone has been released. Expect a GA in Q1 of 2016.
