### ISSUE TITLE
Is it possible to have an advanced configuration of RedisHttpSessionConfiguration ?

### ISSUE THREAD

**Issue by j75** [spring-projects/spring-session#1561]
At the end of javadoc for `EnableRedisHttpSession` it is stated that
``` More advanced configurations can extend RedisHttpSessionConfiguration instead ```

Is there any example somewhere of how to do that? Basically I actually need to replace the bean that creates the `RedisIndexedSessionRepository` with another one that uses my `RedisTemplate` but I can't see how this could be done :-( 

Basically I stumble on errors like
```
The bean 'sessionRepository', defined in org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration, 
could not be registered. A bean with that name has already been defined in class path
resource [... /My.class] and overriding is disabled.
```

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-session/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
