### ISSUE TITLE
Spring Session Support for Hazelcast 4

### ISSUE THREAD

**Issue by mesutcelik** [spring-projects/spring-session#1584]
Hazelcast 4 has recently been released and it is not currently supported.
related : https://stackoverflow.com/questions/60303477/spring-session-with-hazlecast-4

**Comment by fisco-unimatic** [comment]
I've [forked the repo](https://github.com/fisco-unimatic/spring-session), upgraded the hazelcast dependencies, and fixed the code so that it compiles, but there's a failing integration test, `SessionEventHazelcastIndexedSessionRepositoryTests.updateMaxInactiveIntervalTest`. Hz is not firing an entry expired event after we update the time-to-live. (It does if I put breakpoints in, or a thread sleep between updating the ttl on the map and updating the session with the entry processor.)

**Comment by eleftherias** [comment]
@fisco-unimatic Thanks for looking at this issue. 
However, this is schedule for the Spring Session 3.x release because it is a major version upgrade to one of our dependencies.
Since Spring Session 3.x does not have a scheduled release date, I would advise pausing any work on this issue, since it may be a while before it can be merged and any code changes may become stale by then.

**Comment by rwinch** [comment]
Another option is ensuring that we can work with both versions of Hazelcast.

**Comment by mesutcelik** [comment]
Spring Sessions 2.4+ can support Hazelcast 4+. 
Spring Sessions 2.3 and earlier can still support Hazelcast 3.x. 

This can be documented so that everyone can be aware of compatibility requirement.

**Comment by rwinch** [comment]
We can add support for Hazelcast 4, but we must continue to support Hazelcast 3. Our tests should verify that it continues to work as well.

**Comment by vpavic** [comment]
> Spring Sessions 2.4+ can support Hazelcast 4+.

@mesutcelik Spring Session primarily has to align with Spring Boot in terms of managed dependency versions, and since Spring Boot manages those taking semver into account, it's unlikely that upgrade to Hazelcast 4.x will happen before Spring Boot 3.0

It is unfortunate that Hazelcast opted to do so many breaking changes in 4.0 release without ensuring users have a smooth transition period by keeping the old APIs in deprecated form for some time.

**Comment by mesutcelik** [comment]
@vpavic Thanks for the feedback.

A major release had to be done at some point. Every product does that but good news is that 3.12 will be actively supported and this support can be considered as deprecation policy. [See active branches for 3.x](https://github.com/hazelcast/hazelcast/branches/active)

Hazelcast has also clear [Migration Guide](https://docs.hazelcast.org/docs/4.0/manual/html-single/#upgrading-to-4-0-from-prior-versions-3-x) for the documentation of breaking changes. 

In terms of SpringBoot compatibility, Spring Boot 2.2.x works fine with Hazelcast 4 except Spring Boot Actuator. Micrometer needs to give Hazelcast 4 Support first. Once that is resolved then Hazelcast Dependency can be [upgraded to 4.x](https://github.com/spring-projects/spring-boot/blob/e7c265bc3ddc32768180960eb08d14f38c744ba9/spring-boot-project/spring-boot-dependencies/build.gradle#L426)

**Comment by snicoll** [comment]
@eleftherias we are considering moving to Hazelcast 4 with Spring Boot 2.4. We will keep compatibility with Hazelcast 3.x but a default Spring Boot 2.4 app would bring Hazelcast 4. I am not keen to proceed until we have some visibility on this particular issue. 

Based on [another comment of yours](https://github.com/spring-projects/spring-session/issues/1644#issuecomment-640871585) it looks like this is scheduled. Can you please clarify?

**Comment by eleftherias** [comment]
Thanks for pointing that out @snicoll. I have corrected the milestone on this issue to `2.4.0-RC1`.

**Comment by snicoll** [comment]
Thanks @eleftherias. Is there an ETA for a snapshot that includes this fix? I'd like to upgrade but I can't until Spring Session has (optional) support for it. Thanks!

**Comment by eleftherias** [comment]
@snicoll I plan to have a snapshot that includes a fix at the end of next week or the beginning of the following week so that it is ready in time for RC1.

**Comment by eleftherias** [comment]
Configuring a Hazelcast instance requires Hazelcast 4 specific classes.
For example:
<pre>
@Bean
static HazelcastInstance hazelcastInstance() {
	Config config = new Config();
	NetworkConfig networkConfig = config.getNetworkConfig();
	networkConfig.setPort(0);
	networkConfig.getJoin().getMulticastConfig().setEnabled(false);
	AttributeConfig attributeConfig = new AttributeConfig()
			.setName(<b>Hazelcast4IndexedSessionRepository</b>.PRINCIPAL_NAME_ATTRIBUTE)
			.setExtractorClassName(<b>Hazelcast4PrincipalNameExtractor</b>.class.getName());
	config.getMapConfig(<b>Hazelcast4IndexedSessionRepository</b>.DEFAULT_SESSION_MAP_NAME)
			.addAttributeConfig(attributeConfig).addIndexConfig(
					new IndexConfig(IndexType.HASH, <b>Hazelcast4IndexedSessionRepository</b>.PRINCIPAL_NAME_ATTRIBUTE));
	SerializerConfig serializerConfig = new SerializerConfig();
	serializerConfig.setImplementation(new HazelcastSessionSerializer()).setTypeClass(MapSession.class);
	config.getSerializationConfig().addSerializerConfig(serializerConfig);
	return Hazelcast.newHazelcastInstance(config);
}
</pre>

**Comment by eleftherias** [comment]
@snicoll The latest snapshot has the optional support for Hazelcast 4.

**Comment by snicoll** [comment]
@eleftherias thanks for the follow-up. Unfortunately, I can't test the change as the bom currently points to milestone 1 (I've created https://github.com/spring-projects/spring-session/issues/1685). 

The changes look rather involved on the Spring Boot side of things. Do I understand that if Spring Session uses Hazelcast 4

1. We need to Modify how the `HazelcastInstance` is auto-configured. That's certainly something new which we didn't have to do before
2. Users that provide their own `HazelcastInstance` must make sure to set those settings as well.

**Comment by eleftherias** [comment]
@snicoll I updated the BOM to use snapshots.

You are right about the changes involved to configure a `HazelcastInstance` when using Hazelcast 4.

Even aside from the Spring Session changes, the `HazelcastInstance` is different because of the name and method signature changes in Hazelcast 4. For example `MapAttributeConfig` renamed to `AttributeConfig`.
