### ISSUE TITLE
How to save sessions in separate tables each tenant's own DB for JdbcHttpSession under multi-tenancy?

### ISSUE THREAD

**Issue by zhongjiewu** [spring-projects/spring-session#1608]
Based on the tutorials available, I know that session tables will stay in the main datasource. In a multi-tenant architecture, I'd like to store the sessions in tables in tenant's own store. This is for two reasons:

1. Avoid cross-tenant session attack without extra code. If I don't have code to bind session with tenant ids, it's vulnerable to attacks. For example, one can login with "admin" on tenant A and then attach that cookie to a request regarding tenant B. I'll have to write extra code in the to validate.
2. Provide clean data isolation so that if the tenant needs to audit their employee's sessions, I can select these sessions easily without worrying about exposing other tenant's data.

Is there a way to achieve this? I looked into a few solutions (custom SessionRespository, DataSource bean, PlatformTransactionManager bean) but all of them seems to be a configuration that will happen during the initialization phase and will not be switching datasource during each operation. Could you provide some guidance on this issue?

Thanks a lot!

**Comment by rwinch** [comment]
You would probably need a custom SessionRepository with the tenant ID available in context (i.e. a ThreadLocal)

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-session/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
