### ISSUE TITLE
Delete Session without reload it from SessionGrid

### ISSUE THREAD

**Issue by BenSawary** [spring-projects/spring-session#1642]
Hello,

is it possible to extend your SessionRepository interface, to allow delete a session with an existing session-object. In this case we avoid relaoding the session from grid.

**Expected Behavior**
*Interface in spring-session*
```
    /**
     * Deletes the {@link Session} or does nothing if the {@link Session} already deleted.
     * @param session the {@link Session} to delete
     */
    default void delete(S session)
    {
        deleteById(session.getId());
    }
```
*Implementation in spring-session-data-redis*
```
    @Override
    public void deleteById(String sessionId) {
        RedisSession session = getSession(sessionId, true);
        if (session == null) {
            return;
        }

        delete(session);
    }

    @Override
    public void delete(RedisSession session)
    {
        cleanupPrincipalIndex(session);
        this.expirationPolicy.onDelete(session);

        String expireKey = getExpiredKey(session.getId());
        this.sessionRedisOperations.delete(expireKey);

        session.setMaxInactiveInterval(Duration.ZERO);
        save(session);
    }
```
**Current Behavior**

Our session is currently being reloaded from the grid:

redisSessionRepo.delete(redisSession.getId());

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-session/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

You may also find [this section](https://docs.spring.io/spring-session/docs/2.3.0.RELEASE/reference/html5/#custom-sessionrepository) from the reference docs, on customizing the `SessionRepository` useful.
