### ISSUE TITLE
SessionRepositoryUnavailableException when using spring-session-jdbc with webflux

### ISSUE THREAD

**Issue by nagyzsolthun** [spring-projects/spring-session#1660]
**Describe the bug**
When configuring `spring-session-jdbc` based on https://spring.io/projects/spring-session-jdbc#overview with `spring-webflux`, the application fails to start up, and instead throws this exception: `org.springframework.boot.autoconfigure.session.SessionRepositoryUnavailableException: No session repository could be auto-configured, check your configuration (session store type is 'jdbc')`

**To Reproduce**
`mvn spring-boot:run` in the sample project

**Expected behavior**
Application starts up, sessions are stored in the configured database.

**Sample**
https://github.com/nagyzsolthun/spring-reactive-session-jdbc

**Comment by eleftherias** [comment]
Thanks for getting in touch @nagyzsolthun.

When building a reactive web application, currently only Redis and MongoDB can be auto-configured.
Check out [this section](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-session) of the Spring Boot documentation.

Spring Session does not provide a JDBC implementation of `ReactiveSessionRepository`, since JDBC is of a blocking nature.

If it's necessary for you to use JDBC with WebFlux, you could configure a custom implementation of `ReactiveSessionRepository`.

First, make sure you consider whether WebFlux is a good fit for your use case.
From the [Spring Framework documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-framework-choice):
> If you have blocking persistence APIs (JPA, JDBC), or networking APIs to use, then Spring MVC is the best choice for common architectures at least. It is technically feasible with both Reactor and RxJava to perform blocking calls on a separate thread but you wouldn’t be making the most of a non-blocking web stack.

If you decide to implement a custom `ReactiveSessionRepository`, you may find [this section](https://docs.spring.io/spring-session/docs/current/reference/html5/#custom-sessionrepository) of the Spring Session docs useful.

**Comment by nagyzsolthun** [comment]
Thank you for the details explanation @eleftherias, much appreciated.
