### ISSUE TITLE
 How to dynamically set the ttl value of session in redis

### ISSUE THREAD

**Issue by zengxiangjiang** [spring-projects/spring-session#1714]
Hello, I have a question. How to dynamically set the ttl value of session in redis？

**Comment by RKaczmarek** [comment]
i'd say you should just configure the http session timeout.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
