### ISSUE TITLE
Is there any way to support HttpSessionIdResolver under webflux

### ISSUE THREAD

**Issue by BruceAn1978** [spring-projects/spring-session#1735]
**Expected Behavior**

I have customized HttpSessionIdResolver successfully under spring boot, but I can not find any docs by webflux.
I am working by spring cloud now, so I wang to customize the HttpSessionIdResolver under Spring Cloud Gateway(WebFlux).

**Current Behavior**
HttpSessionIdResolver can not work under Spring Cloud Gateway(WebFlux).

**Context**
How to do it under Spring Cloud Gateway(WebFlux).

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Briefly, I believe this question has already been asked on Stack Overflow. [This question](https://stackoverflow.com/questions/46745494/how-to-use-spring-websessionidresolver-with-spring-security-5-in-a-spring-webflu) may be the same question you have. 

You may also find [this section of the documentation](https://docs.spring.io/spring-session/docs/2.4.1/reference/html5/guides/boot-webflux-custom-cookie.html) useful.
