### ISSUE TITLE
Need to specify custom session cookie name

### ISSUE THREAD

**Issue by SMakhrov** [spring-projects/spring-session#1737]
**Expected Behavior**

SESSION cookie name can be changed to any name.

**Current Behavior**

SESSION cookie name cannot be changed to any name.

**Context**

Hi!

We have multiregional API with session cookie in each of 4 regions.
By default in spring-session I can use only one variant of session cookie name - it's "SESSION".
But in our multiregional case we need API in each of 4 regions where will be region-specific session cookie name.
For example: SESSION-EUC1, SESSION-USW2, SESSION-APN1,...

Could I ask you to add feature in spring-session for specifying name of cookie? I have tried different tips around all Internet and stackoverflow but didn't find solution.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Briefly, you can already customize the session cookie name. Check out the Spring Session documentation, specifically [the section about customizing the session cookie](https://docs.spring.io/spring-session/docs/current/reference/html5/guides/java-custom-cookie.html).
