### ISSUE TITLE
Need to use session cookie which have been sent in request

### ISSUE THREAD

**Issue by SMakhrov** [spring-projects/spring-session#1738]
**Expected Behavior**

If received session cookie header then this cookie will be used by spring-session and will not created new one.

**Current Behavior**

If received session cookie header then it will be ignored by spring-session and will created new one.

**Context**

Hi! 

I need to benchmark Spring projects (for example Spring Cloud Gateway). Benchmark required use prepared session which. And it's required to use session from session cookie header if the last one was sent.

**Comment by SMakhrov** [comment]
Example of request here. I'm sending cookie SESSION with value 123:

> GET /index.html HTTP/1.1
> Host: localhost
> User-Agent: insomnia/2020.4.2
> Cookie: SESSION=123
> Accept: */*

In response I see that my cookie will be changed by Set-Cookie header:

< HTTP/1.1 200 OK
< Date: Thu, 26 Nov 2020 12:17:28 GMT
< Last-Modified: Tue, 24 Nov 2020 16:26:04 GMT
< Accept-Ranges: bytes
< Content-Type: text/html
< Content-Length: 17
< Set-Cookie: SESSION=98033636-0a15-41eb-94a8-efba110aa261; Path=/; HttpOnly; SameSite=Lax

I need an option where I can disable such behaviour of spring-session if I need use existent session cookie.

**Comment by eleftherias** [comment]
This behaviour is not specific to Spring Session. The web application only accepts server side generated session ID
values.

Could you explain why you would want the application to accept an unknown value as the session ID?

**Comment by SMakhrov** [comment]
I'm going to benchmark Spring Cloud Gateway. AFAIK it uses spring-session.
My scenario check metrics for already authorized users which will have prepared cookies.
I'm going to use in Redis as cookie storage and put there prepared session ids.
So on server side will be prepared cookies.

**Comment by eleftherias** [comment]
> AFAIK it uses spring-session.

Spring Cloud Gateway does not include Spring Session by default. You would need to include it in your application's dependencies if you want to use it.
Since you mention that your are using Redis as the cookie storage, does that mean you are using Spring Session Data Redis?

If this is the case, you need to ensure that all of the session data is set up correctly in Redis. 
You can read about how the session is stored in [this section](https://docs.spring.io/spring-session/docs/2.3.1.RELEASE/reference/html5/#api-redisindexedsessionrepository-storage) of the reference documentation.

However, it may be simpler to perform your tests with an existing cookie that is created by your application.
Then you would not need to prepopulate the data in Redis or any other data store.
In the issue description that value is "98033636-0a15-41eb-94a8-efba110aa261".

I will close this issue as answered, but feel free to reach out if you think there is a bug in Spring Session.
