### ISSUE TITLE
Add validation and capability for OAuth2User and defaultOidcUser in sping-session jdbc

### ISSUE THREAD

**Issue by MisterHat-89** [spring-projects/spring-session#1749]
Good day!
Sorry for my English.

At the moment, the PRINCIPAL NAME INDEX_NAME parameter can be correctly picked up and entered into the database when the number (ID) is there.

But when an object comes to this attribute, then an error occurs in your code.
I am doing OAuth2 and OidcUser authorization on the site (Via social networks).
I would like to integrate your code additionally so that session data will be added to the database.

I wanted to inherit the Spring Session RememberMeServices, SpringSessionBackedSessionInformation classes, rewrite the methods, but they are not public.
And there is not enough experience to recompile the plugin (((
I tried to hijack the session and add my data to PRINCIPAL_NAME_INDEX_NAME, but it didn't work ((
At least bind to an object so that there is an id and object.getId () is added to PRINCIPAL_NAME_INDEX_NAME

Please help me, I couldn't do this on my own.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
