### ISSUE TITLE
Allow dynamic value for SameSite attribute in DefaultCookieSerializer

### ISSUE THREAD

**Issue by chrisrhut** [spring-projects/spring-session#1793]
**Expected Behavior**

It would be great if we were able to configure `DefaultCookieSerializer` to set `SameSite=None` _but only if_ the current request is `Secure`. A possible implementation might be to add a method overload such as:

```java
public void setSameSite(Function<HttpServletRequest, String> mapper) {
  this.sameSiteMapper = mapper;
}

public void writeCookieValue(CookieValue cookieValue) {
  // ...
  if (this.sameSiteMapper != null) {
    sb.append("; SameSite=").append(this.sameSiteMapper.apply(request));
  }
}
```

**Current Behavior**

The `SameSite` string value must be configured ahead of time (during bean definition) keying off some externalized configuration such as an environment variable or profile. Care must be taken to avoid an invalid configuration such as setting the `SameSite=None` attribute _without_ setting secure to true.

**Context**

Browsers reject cookies with the `SameSite=None` attribute unless the `Secure` attribute is also set. During development (e.g. on a `localhost:8080` environment) `Secure` will never be true; the implementation already handles this for you by checking the value of `HttpServletRequest#isSecure` at the time the cookie is written. This way we automatically get secure cookies in production.

It would be great if we could similarly tell the DefaultCookieSerializer, "set SameSite attribute to None if and only if the request is secure", but unfortunately currently it has to be set statically ahead of time. That means that we must rely on some external configuration (e.g. checking the runtime Spring `profile` or another environment variable) when configuring the bean.

**Comment by eleftherias** [comment]
@chrisrhut 
As you mentioned, you can achieve this by writing a custom `CookieSerializer`.
In your implementation, you could delegate to a `DefaultCookieSerializer` when necessary, and write a custom implementation of `writeCookieValue`.

Regarding your specific use case, it seems like you want to set a different value for the SameSite attribute depending on whether you are in development or production.
I would generally advise against this, since it may cause unexpected (and untested) behaviour in production, which may lead to a vulnerability in your application.
You might consider using HTTPS in your local environment instead to closer mimic production.

**Comment by chrisrhut** [comment]
Thank you for the reply, @eleftherias. What you said makes sense particularly about the different environments, and I agree it could be the cause of unexpected bugs or vulnerabilities and that using HTTPS locally would be a better long-term solution.

The one part of your response that's less clear is:

> delegate to a `DefaultCookieSerializer` when necessary, and write a custom implmentation of `writeCookieValue`

As far as I can tell, the [default implementation of `writeCookieValue()`](https://github.com/spring-projects/spring-session/blob/2.4.2/spring-session-core/src/main/java/org/springframework/session/web/http/DefaultCookieSerializer.java#L157-L160) takes complete control of not only rendering the cookie, but also adds the `Set-Cookie` header to the servlet response, meaning there doesn't seem to be a viable hook to override/delegate as you described.

So perhaps a better/different enhancement request might be to split those two steps (rendering the cookie header _value_ as a `String`, vs adding it as a response header) to give subclasses or delegates the chance to customize the cookie before calling `response.addHeader()`? Do you think the team would entertain an issue (or PR) along those lines?

**Comment by eleftherias** [comment]
@chrisrhut I will preface this by saying it is better to use a Spring profile to distinguish between production and development environments, than having that logic in your code.

If you want to change the cookie serialization based on whether the request is secure, you could have a custom `CookieSerializer` that delegates writing the cookie to different `DefaultCookieSerializers`. In this case it will call a `DefaultCookieSerializer` with the SameSite attribute set to `null` if the request is secure, otherwise it will call a different serializer.

```
public class CustomCookieSerializer implements CookieSerializer {
	// ...

	@Override
	public void writeCookieValue(CookieValue cookieValue) {
		if (cookieValue.getRequest().isSecure()) {
			noneCookieSerializer.writeCookieValue(cookieValue);
		} else {
			otherCookieSerializer.writeCookieValue(cookieValue);
		}
	}
}
```

**Comment by chrisrhut** [comment]
Thank you for clarifying your delegation idea, that makes a lot more sense. We actually ended up using profiles as you said to provide different beans for our different environments. Thanks again!
