### ISSUE TITLE
can not changesessionId in authentication

### ISSUE THREAD

**Issue by taagholi** [spring-projects/spring-session#1804]
Hi
I have a project that uses tomcat 8 and Java EE Security, I just added it to the spring-session-redis project, with the new spring-session changes the whole business works fine, but the login homepage that posts the form to j_security_check and then Goes from authentication to welcome-page, changes the sessionId of  httprequest in this scenario, and causes the next servlet where I want the captcha information to be null. Of course, I checked with the previous config and it also changes the sessionId, but in the internal tomcat-catalania classes, exactly the AuthenticatorBase class of the register method changes the sessionId, and this causes the previous session information to be transferred to the new session, and as a result session The new one has the previous captcha information and there is no problem but in spring-session-redis this does not happen, can you help me?
Thankful

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
