### ISSUE TITLE
custom HashValueSerializer failure

### ISSUE THREAD

**Issue by zhangran2616** [spring-projects/spring-session#1848]
![image](https://user-images.githubusercontent.com/6472032/117427344-89921580-af57-11eb-9917-0270dc740785.png)
i autowire this bean,but it didn't work
![image](https://user-images.githubusercontent.com/6472032/117427750-f1486080-af57-11eb-84ef-a0daea314afd.png)

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
