### ISSUE TITLE
Example with Xml configuration

### ISSUE THREAD

**Issue by xuzw12** [spring-projects/spring-session#185]
Is there any example use xml configuration? Sometimes annotation is not suitable.Thanks~

**Comment by rwinch** [comment]
There is no guide yet (see #139), but there is a sample application. See [httpsession-xml](https://github.com/spring-projects/spring-session/tree/ba07c1d5620f290eb5ee8a853c748019182d8345/samples/httpsession-xml) Note that the sample has since been updated to take advantage of #105 which has not yet been released, so you will need to use the version of the sample I linked to until 1.0.1 is released.
