### ISSUE TITLE
Allow persistence of session in cookies(encrypted for sure)

### ISSUE THREAD

**Issue by bhagwat** [spring-projects/spring-session#186]
There is a nice Grails plugin for managing Http session in cookies : https://github.com/benlucchesi/grails-cookie-session-v2 . This way we can achieve **simplified Scaling** and **fault tolerance** (well explained on [github page] (https://github.com/benlucchesi/grails-cookie-session-v2#cookie-session-grails-plugin) ). The plugin deals with [Replay attacks] (https://github.com/literalice/grails-cookie-session#replay-attacks) issue nicely. 

Good part is that your application does not need to be stateful or depend on some external fast access databases like memcache/redis, thus saving cost and maintenance.

**Comment by rwinch** [comment]
@bhagwat Thanks for the report

> The plugin deals with [Replay attacks] (https://github.com/literalice/grails-cookie-session#replay-attacks) issue nicely. 

How does it deal with Replay attacks? The link you provided states:

> You should be aware of the replay attacks when you use the cookie based session store.
Even if someone sniffs a user's cookie, and replay the cookie to your application, the application cannot detect this. (they may log in to your application or ...).

This doesn't seem to deal with the issue so much as state that it is a problem.

**Comment by bhagwat** [comment]
The link above was for pointing out the issue that has been addressed/fixed by the  [new plugin](https://github.com/benlucchesi/grails-cookie-session-v2). Please check [this link](https://github.com/benlucchesi/grails-cookie-session-v2#relationship-to-grails-cookie-session-plugin-version-012). While fixing the replay attack issue, the author ended up rewriting the whole plugin.

**Comment by rwinch** [comment]
Thanks for the reply. I don't see how the new plugin is addressing it. Perhaps you can highlight the particular section that details this? Generally speaking, you cannot avoid replay attacks with some sort of state (i.e. using a nonce). As soon as you introduce state, you might as well have used a session in the first place.

At first glance, the implementation seems generally insecure. As I am reading it, the cookies are encrypted instead of being signed which provides no guarantees of authenticity (except for when using [Authenticated Encryption](http://en.wikipedia.org/wiki/Authenticated_encryption)). Please see my blog on [Exploiting encrypted cookies for fun and profit](https://spring.io/blog/2014/01/20/exploiting-encrypted-cookies-for-fun-and-profit) for an example of exploiting encrypted cookies.

**Comment by bhagwat** [comment]
Thanks @rwinch for nice explanation on exploiting encrypted cookies. I am closing the issue as there is no point in opening a new  discussion thread here as it is already done on the article you have wrote  [Exploiting encrypted cookies for fun and profit] (https://spring.io/blog/2014/01/20/exploiting-encrypted-cookies-for-fun-and-profit).

**Comment by divick** [comment]
@rwinch Rob, as you mentioned that the session cookie can be signed and encrypted too for client side cookie store. So does spring not provide any implementation for having signed and encrypted session cookies?

**Comment by rwinch** [comment]
@divick We do not provide a way to sign and encrypt the cookies.
