### ISSUE TITLE
Requested Session invalidated if session is not accessed

### ISSUE THREAD

**Issue by sirianni** [spring-projects/spring-session#188]
```java
		private boolean isInvalidateClientSession() {
			return currentSession == null && isRequestedSessionIdValid();
		}
```
I believe this is missing a `!`  in front of `isRequestedSessionIdValid()`

**Comment by rwinch** [comment]
What makes you think that? The method is suppose to represent if a client requested a valid session id and the session is no longer valid (i.e. was the session valid when the client requested it but it was invalidated at some point).

**Comment by sirianni** [comment]
The issue I'm seeing is that valid sessions are getting erroneously invalidated.

`currentSession` can be `null` if `Request.getSession()` was never called by application code during the lifetime of the request (which is a perfectly valid scenario).  In this case, `isRequestedSessionIdValid()` still returns true because the sessionId is still valid.  However, this triggers Spring session to invalidate the session, thereby removing the cookie.

Why would we want to invalidate the client session if the sessionId *is* valid?

**Comment by rwinch** [comment]
This does appear to be a bug. However the proposed solution will break other scenarios. For example, if an invalid session (i.e. no session) is requested by the client we do not want to invalidate the session.

**Comment by sirianni** [comment]
Also, it would be nice if the solution did not require fetching the session just to perform this check.  i.e. skip the check entirely if `currentSession` is null.

In other words, the `SessionRepository` should not get hit if the application did not call `getSession()`, during a request lifecycle.  This would help performance for requests to unprotected URLs (i.e. those that serve static content).

**Comment by rwinch** [comment]
@sirianni I have pushed a fix for the originally requested issue. Please try out the [latest snapshot](http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/httpsession.html#updating-dependencies) to verify your issue is fixed.

> Also, it would be nice if the solution did not require fetching the session just to perform this check. i.e. skip the check entirely if currentSession is null.
>
> In other words, the SessionRepository should not get hit if the application did not call getSession(), during a request lifecycle. This would help performance for requests to unprotected URLs (i.e. those that serve static content).

I don't think there should be an issue with `SessionRepository` being invoked if getSession() is not invoked. I have [added a test](https://github.com/spring-projects/spring-session/commit/f7118763470e58e5430c336ad217c76c82fbeba4) to verify this is correct.

If you believe this to be an issue, please create a new ticket with details outlining how to reproduce the issue. If this is not an issue, a response confirming as such would be much appreciated.

Thanks so much for helping make Spring Session better!
