### ISSUE TITLE
spring-embedded-redis-1.0.1.RELEASE.jar not pulled by my gradle build

### ISSUE THREAD

**Issue by balteo** [spring-projects/spring-session#190]
I have recently upgraded to spring session 1.0.1.RELEASE but it seems that the spring-embedded-redis-1.0.1.RELEASE.jar dependency is not pulled by gradle.

Has anyone else experience the issue?

Here is my gradle config:

   ext.springSessionVersion = "1.0.1.RELEASE"
   ...		
   // Spring Session
   compile("org.springframework.session:spring-session:${springSessionVersion}")
   compile("org.springframework.session:spring-session-data-redis:${springSessionVersion}")

**Comment by rwinch** [comment]
I'm not sure I understand  your problem. Do you expect one of those dependencies to pull in spring-embedded-redis automatically? There is no plans to bring in the embedded database since this is not a production dependency. It is only intended to make running locally easy.

NOTE The spring-embedded-redis is only intended to be an internal dependency for samples right now. See see #121 for discussion about externalizing support for embedded Redis

**Comment by balteo** [comment]
I mean with the above declared gradle dependencies, @EnableEmbeddedRedis is not on the classpath...

**Comment by rwinch** [comment]
Thanks for the clarification.

* EnableEmbeddedRedis is only intended for the sample applications. The reason is that we have not had enough time to solidify the code to guarantee passivity and because we believe it makes more sense in Spring Data Redis than Spring Session. See #121 for discussion about making this available for general usage
* An embedded Redis instance will never be brought in automatically by spring-session or spring-session-data-redis since embedded redis is for testing only. Bringing an embedded Redis instance in transitively with spring-session would be like spring-orm having a transitive dependency on hsqldb. Once #121 is addressed, you would be able explicitly bring in an embedded Redis instance.

In the meantime, you are free to copy the code from [spring-embedded-redis](https://github.com/spring-projects/spring-session/tree/1.0.1.RELEASE/samples/spring-embedded-redis) and include it within your own project. Please also vote on #121 so we can prioritize it appropriately.

I'm going to close this as I believe it should answer your question. If it does not, please reopen and clarify what your confusion is.

Thanks again!

**Comment by balteo** [comment]
Thanks a lot for the clarification Rob.

2015-04-16 18:07 GMT+02:00 Rob Winch <notifications@github.com>:
