### ISSUE TITLE
Continuation Of Discussion On Issue #1916

### ISSUE THREAD

**Issue by jas34** [spring-projects/spring-session#1919]
@eleftherias I had opened issue #1916. Unfortunately, that discussion has been closed without the conclusion of discussion points. I had requested to reopen the issue in my [comment](https://github.com/spring-projects/spring-session/issues/1916#issuecomment-927721000) to conclude the discussion.

Not sure whether that issue will be reopened so creating this issue to continue and conclude the discussion.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements, rather than discussions. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
