### ISSUE TITLE
commitSession() called twice

### ISSUE THREAD

**Issue by fe2s** [spring-projects/spring-session#198]
Hi,

I'm developing custom SessionRepository.

I noticed that SessionRepositoryRequestWrapper.commitSession() called twice
- onResponseCommitted
- in doFilterInternal, finally block

This causes two calls of sessionRepository.save(session) and leads to persisting session to external storage twice.

What's the reason to commitSession() twice?

**Comment by rwinch** [comment]
it is necessary to persist the session as soon as the response is committed to ensure the session is available to the clients as soon as the client has access to the session id. Consider the following scenario:

* Request A: A user is authenticated and placed into session
* Request A: The response is committed (but not totally completed) with a particular session id
* Request B: The client gets the (partial) response from Request A and then makes Request B with the session id
* Request B: The server looks for the session but it is not found because while the response was committed and the client could see it the Filter invocation did not complete
  
It is necessary to write after the session is committed because further modifications to the session might be made. For example:

* Request A: A request for a session is made
* Request A: the session is updated with user=first
* Request A: The response is committed (so the session is written)
* Request A: The session is updated with user=second
* What is going to ensure the session is written without having the finally blocK?

It is generally recommended for a SessionRepository implementation to keep track of changes to ensure that only deltas are saved. You can see that this is how the Redis implementation provided with Spring Session behaves.

Does this make sense now?

**Comment by fe2s** [comment]
Got it. Thanks

**Comment by cemo** [comment]
It might be a good idea to add this into documentation. Thanks for detailed information.

**Comment by rwinch** [comment]
@cemo Thanks for the suggestion. We will include your suggestion in #199

**Comment by zeronone** [comment]
When Spring's session-scoped beans are used, it is actually committed only in the second time (in the finally block). This can be very confusing to the users. 

Also from the performance viewpoint, it is bad. But Spring session scoped beans are always set using `Session#setAttribute`, so it is always saved back to the repository. [link](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/context/request/ServletRequestAttributes.java#L273)

Is there any configuration or settings that would store all the changes in one round.
