### ISSUE TITLE
Session is not saved after redis repository creates it.

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-session#202]
My problem is described here:

http://stackoverflow.com/questions/29539781/session-is-null-on-first-request/29640179

but once again: I have a filter which checks to see if there's default language (or user, or currency, etc) in the session and then if not does the following:
````
HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.currentRequestAttributes()).getRequest();

final String sessionIds = request.getSession().getId();

// DO some stuff with the sessionID
Session session = sessionRepository.getSession(sessionId);
````

However, from what I see the flow goes like this: to get the `sessionId` I do `request.getSession().getId()` calls `SessionRepositoryFilter` which calls `RedisOperationsSessionRepository` which creates the session but does *NOT* save it in Redis!!!.. So now I have the `sessionId` but because it is not saved in redis when I call `sessionRepository.getSession(sessionId);` the repository returns `null` so all my logic throws exceptions.

I think the `RedisOperationsSessionRepository` must save the session as soon as it creates it and returns it to the client - otherwise people will try to query for it and the repository will return `null`

**Comment by zampettim** [comment]
I'm seeing similar behavior, in a Spring Boot/Spring Cloud suite of micro-services. We have implemented a Gateway application on Spring Boot with the Zuul Proxy that guards all of the access to the backend services. All of the services are configured to use a shared Redis instance for their session management. The Gateway is configured in Spring Security/Spring Web to require authentication for almost all endpoints, using the CookieHttpSessionStrategy. On successful login, the Gateway resumes the user's request and forwards the request to the backend service. But things fail because the session does not yet exist. If I then re-send the same exact request, everything works.

I've confirmed that the Gateway is creating the session object and is passing the correct information on to the backend service. But it appears that the session is not being saved to Redis as part of the initial Session creation.

**Comment by rwinch** [comment]
My question for you is...why are you using the repository in the first place? Why not just use 

```java
HttpSession session = HttpServletRequest.getSession();
```

Regardless, I think between #202 and #249 this will no longer be an issue. What are your thoughts?

**Comment by cryptonite** [comment]
I'm facing a similar issue as mentioned by @zampettim. I've posted about it on SO: http://stackoverflow.com/questions/34449447/spring-netflix-zuul-authenticate-and-route-the-same-request.

This seems to be happening due the fact that session is persisted in finally block in *SessionRepositoryFilter.doFilterInternal()*: 
```
try {
    filterChain.doFilter(strategyRequest, strategyResponse);
} finally {
    wrappedRequest.commitSession();
}
```
This makes the session unavailable from redis or to downstream microservices till all filters are executed on the gateway. Is there some way to persist the session before the requests get routed by Zuul?

**Comment by steve-donovan** [comment]
Hi
Did any of you find a solution to this? It sounds like we all share same issue. I thought maybe CORS issues as there arent any appropriate headers on first 403, but i also noticed 2 sessions create in Redis, one with my extra authentication attribs, and one without.
also noticed
good one has : sessionAttr:SPRING_SECURITY_CONTEXT
bad one : sessionAttr:SPRING_SECURITY_SAVED_REQUEST

**Comment by rwinch** [comment]
@steve-donovan This issue should be resolved now via https://github.com/spring-projects/spring-session/issues/273 1.1.0.RC1+ has added an option to write immediately. See http://docs.spring.io/spring-session/docs/1.1.0.RC1/reference/html5/#api-redisoperationssessionrepository-config

**Comment by fcjreed** [comment]
This is still not fixed as of version 1.3.0. Can this be reopened? I have tested like this:
@EnableRedisHttpSession(redisFlushMode=RedisFlushMode.IMMEDIATE) 

HttpSession session = httpRequest.getSession(true);

String sessionId = session.getId();

Session session = sessionRepository.getSession(sessionId);

Session here is null..

Am I missing something? For distributed services, using redis for externalized session with a large set of data to cache makes accessing the session very slow as you have one single namespace supporting n services. The reason why I'm accessing the session repository is because I'm trying to establish multiple namespaces per domain by dynamically changing on session access.

**Comment by rwinch** [comment]
@fcjreed Can you create a separate ticket and explain your use case in more detail?

**Comment by patriceo** [comment]
Hi @rwinch @fcjreed , I'm having the same issue too with the 1.3.0.RELEASE version. I have been debugging for an hour and I think I have isolated what is going on.

I'm having 2 spring boot applications.

1/ A zuul gateway which implements a basic authentication security and using spring session redis. 
2/ Another spring boot application also using spring session redis and which implements a rest api.

If I try to call my secured rest api using postman it fails the first time because even if my gateway authenticates me successfully, when the api controller handle my request it does not see the persisted user details object in redis and see me as anonymous user. The second time it works fine because the spring security object are already persisted in redis.

If I try to call my api using curl command line, providing right credentials, I always get a 403 because I guess it's using different session every time so rest api never gets my spring security user details from redis.

I have tried to set RedisFlushMode.IMMEDIATE to the redisFlushMode of @EnableRedisHttpSession but still the same behaviour.

**Comment by patriceo** [comment]
After further investigation I finally solved it as described here : https://stackoverflow.com/questions/34751700/spring-zuul-api-gateway-with-spring-session-redis-authenticate-and-route-in-sa?rq=1#answer-38867506

Basically:
-flushMode set to RedisFlushMode.IMMEDIATE
-add a pre filter to add the cookie with the session id in headers
