### ISSUE TITLE
Subproject spring-session-data-mongodb won't compile on Windows CP1252

### ISSUE THREAD

**Issue by fabio-grassi-gbs** [spring-projects/spring-session#2053]
**Describe the bug**
On Windows PC with Italian code page Windows 1252, building the project from source either by Gradle Wrapper o by Eclipse fails because of an illegal char constant. More precisely the constant is in MongoSession class and is named DOT_COVER_CHAR. A comment makes clear the intention to use a "very rarely used character". Unfortunately it appears that the encoding of the character gets messed on my machine and I end up having a char constant which is in fact the 3 chars long and this is illegal.

**To Reproduce**
Checkout the project on a Windows 1252 machine and run ./gradlew build.

**Expected behavior**
The project should compile successfully.

**Sample**
[build_failed.log](https://github.com/spring-projects/spring-session/files/8472425/build_failed.log)

**Comment by gregturn** [comment]
It appears the issue may be Windows lack of support for something that compiles on UTF-8 based systems. We build everything on Linux for CI and releases. Some of the reading I did mentioned that Windows heavily uses UTF-16, which is more limiting than UTF-8. Despite the gradle directing javac to compile with UTF-8 encoding, this appears to break.

Have you used the binaries on Windows servers? And do they work? 

Because to alter the character used in this scenario would possibly be deemed a breaking change since existing users of the system are counting on the "right" character being there to translate dotted field names.

**Comment by gregturn** [comment]
Well, gee, looks like once, long ago, this WAS covered by a unicode character!

https://github.com/spring-projects/spring-session-data-mongodb/commit/d601e270fc4099e2167dd9b72f1054e6b293e76b#diff-57190a47726099e31fdf86b12b80206e2ae24feb28aacaf494b99557583df150L47

Looks like the de-lomboking effort somehow converted the unicode representation into a UTF-8. Probably the plugin did that.

**Comment by gregturn** [comment]
@fabio-grassi-gbs Can you check out the branch I pushed to the repository and see how this new unit test runs for you?

I basically tracked down the unicode representation we original used for the DOT_COVER_CHAR and want to see if it works for you. If so, I'll migrate to that and remove this temporary unit test.

**Comment by fabio-grassi-gbs** [comment]
I am not able run the temporary test as it won't compile for the very same reason the original code doesn't compile: invalid character constant. I think the only way to go is revert the constant to the original value '\uF607'.

**Comment by gregturn** [comment]
Try it now!

**Comment by fabio-grassi-gbs** [comment]
Ok, now it works! Thanks, FG
