### ISSUE TITLE
Why type conversion long to int about session's "maxInactiveInterval"?

### ISSUE THREAD

**Issue by GracefulSoul** [spring-projects/spring-session#2130]
Hello!  :)
As you know, the Duration.getSeconds() method returns a long type about duration in seconds.
However, if you look at the code below and use it in excess of the maximum value (2147483647) by converting it to int type, an overflow may occur.
I wonder why you keep using this code and database's schema.

https://github.com/spring-projects/spring-session/blob/38a87e093a9b9b18ea0cdad26577d397d300cfa9/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcIndexedSessionRepository.java#L832

**Comment by vpavic** [comment]
It should not be possible for `maxInactiveInterval` to overflow here since Servlet's `HttpSession#getMaxInactiveInterval` itself returns `int`. Note that before moving temporal properties to `java.time` in Spring Session 2.0, the equivalent session property we had was named `maxInactiveIntervalInSeconds` and was also of type `int`.

**Comment by GracefulSoul** [comment]
I know that Servlet's `HttpSession#getMaxInactiveInterval` itself returns `int`.
To keep some desired sessions for 68 years (68.09625973=2147483647/(365×24×60×60×60), it is believed that unwanted overflows can occur because long type calculated by `Duration#ofSeconds` can be sent directly from the backend to `HttpSession#setMaxInactiveInterval`.

**Comment by vpavic** [comment]
> I think we should consider expanding rather than using downcasting to maintain the existing type.

I'm not sure what you really mean by this, but we cannot change the Servlet API. Since `maxInactiveInterval` is of type `int` over there, we have to respect that.

I'll look into this a bit deeper and consider some additional safety measures in case someone attempts to use `Session` API directly to set `maxInactiveInterval`, instead of `HttpSession` (which is what really should be user-facing API).

**Comment by GracefulSoul** [comment]
I'm glad "some additional safety measures in case someone attempts to use `Session` API directly to set `maxInactiveInterval`" is one of the answers I want.
It doesn't mean much because I can use it in the form I want, but someone left this article to save me the trouble of analyzing the code for this project.
Well, I hope you have a great day! :)
