### ISSUE TITLE
using MapSession

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-session#217]
seems very unclear how to use MapSession, and it seems like it would be especially beneficial for tests or a development server.

this is what I tried for this

https://github.com/xenoterracide/spring-session-redis-test-case/blob/inmemory/src/main/java/com/xenoterracide/Application.java

~~~
@RestController
@SpringBootApplication
public class Application {

	@RequestMapping( "/" )
	public String greeting() {
		return "hello";
	}


	@Configuration
	@Order( SecurityProperties.ACCESS_OVERRIDE_ORDER )
	protected static class SecurityConfiguration extends WebSecurityConfigurerAdapter {


		@Bean
		static SessionRepository<? extends ExpiringSession> repository() {
			return new MapSessionRepository( );
		}


		@Bean
		static HttpSessionStrategy httpSessionStrategy() {
			return new HeaderHttpSessionStrategy();
		}

		@Autowired
		void globalUserDetails( final AuthenticationManagerBuilder auth ) throws Exception {
			auth.inMemoryAuthentication().withUser( "admin" ).password( "admin" ).roles( "USER", "ADMIN" );
		}

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http.httpBasic()
					.and()
					.authorizeRequests()
					.anyRequest().authenticated();
		}
	}

	public static void main( final String[] args ) {
		SpringApplication app = new SpringApplication( Application.class );
		app.setShowBanner( false );
		app.run( args );
	}
}
~~~

worth noting I did ask about this on SO
http://stackoverflow.com/q/30519774/206466

**Comment by benneq** [comment]
I simply did this inside a Spring Boot application and it works just fine:

```
@Configuration
public class HttpSessionConfig {
	@Bean
	public <S extends ExpiringSession> SessionRepositoryFilter<? extends ExpiringSession> springSessionRepositoryFilter(SessionRepository<S> sessionRepository, ServletContext servletContext) {
		SessionRepositoryFilter<S> sessionRepositoryFilter = new SessionRepositoryFilter<S>(sessionRepository);
		sessionRepositoryFilter.setServletContext(servletContext);
		return sessionRepositoryFilter;
	}
	
	@Bean
	public SessionRepository<?> sessionRepository() {
		MapSessionRepository sessionRepository = new MapSessionRepository();
		return sessionRepository;
	}
}
```

This is more or less copy and pasted from `org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration`. This class contains everything that happens when you do `@EnableRedisHttpSession`.

**Comment by xenoterracide** [comment]
> I simply did this inside a Spring Boot application and it works just fine:

for me it doesn't compile, because SessionRepositoryFilter does not have a setServletContext method... http://docs.spring.io/spring-session/docs/1.0.0.RELEASE/api/ though it appears that has changed in a more recent version... (which isn't in Spring Platform yet)

**Comment by rwinch** [comment]
@xenoterracide - Thank you for your feedback.

Generally MapSession is not recommended because:

a) It is not "full featured". Specifically, it does not fire SessionDestroyedEvents and thus will not work with WebSocket support.
b) Unless you use a distributed Map implementation it does not work for session expiration
c) You also need to ensure your Map implementation supports cleaning up of expired sessions so that you do not end up with a ton of expired sessions.

Yes it might be useful for tests and development. However, if you are willing to accept these differences in development and your tests it is typically just easier to not add Spring Session in these instances.

> for me it doesn't compile, because SessionRepositoryFilter does not have a setServletContext method... http://docs.spring.io/spring-session/docs/1.0.0.RELEASE/api/ though it appears that has changed in a more recent version... (which isn't in Spring Platform yet)

This was added to get around Servlet 2.5 issues. If you are on Servlet 3.0+ you can just skip setting the ServletContext on SessionRepositoryFilter.

**Comment by rwinch** [comment]
You can easily use [@EnableSpringHttpSession|http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/#api-enablespringhttpsession] to use the `MapSessionRepository`
