### ISSUE TITLE
Autoconfigure JdbcIndexedSessionRepository based on DB type

### ISSUE THREAD

**Issue by mwisnicki** [spring-projects/spring-session#2202]
Is there a reason why JdbcIndexedSessionRepository implementations such as SqlServerJdbcIndexedSessionRepositoryCustomizer are not automatically enabled?

**Comment by marcusdacoregio** [comment]
Hi @mwisnicki,

This sounds to me like a good fit for Spring Boot instead of Spring Session since Spring Boot already detects which database you're working with, and acts on that information in several aspects of its auto-configuration facilities. That said, it should be the best fitting place to automatically apply the customizer.

Can you do a search on their issue tracking and see if there is not an issue created for that? If so, you can go ahead and create one.
