### ISSUE TITLE
Session metadata handling

### ISSUE THREAD

**Issue by ractive** [spring-projects/spring-session#223]
A common usecase when dealing with sessions is to show the user his current sessions with the IP, creation date and the location from where the session has been created (geo location of IP).

spring-session should provide a way to store metadata for a session. This metadata should be kept separate from the session attributes. A set of default metadata should always be provided by spring-session (like the remoteAddr). Other useful metadata providers would be available as well, e.g. one that sets the username for successful spring security authentications. A mechanism to register own "MetadataProvider"s would be nice so that own data could be provided.

**Comment by chrylis** [comment]
Can you explain in more detail the need for a complicated API addition that seems to just be replicating the functionality of session attributes?

**Comment by rwinch** [comment]
@ractive Spring Session can be used in non web applications (i.e. Spring Integration). This makes it very difficult to anticipate what meta data is necessary. Instead, this is up to individual users to provide. This is very easy for consumers of Spring Session because it can be placed in a session attribute's value.

**Comment by ractive** [comment]
The [findbyusername sample](http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/findbyusername.html) posted for issue #7 exactly tackles this problem. In the sample definition there a sentence:

> We plan to provide first class integration with Spring Security to make this process [populating the username] easier in the future. For details track gh-266.

I still would like to see a more generic approach to handle any metadata - where the username is just one of them. The mentioned `SpringSessionPrincipalNameSuccessHandler` would be one metadata provider besides others (like remote IP etc.).

**Comment by rwinch** [comment]
I think the problem is that everyone is going to have their own meta data that they are interested. Furthermore I think it will be likely users are interested in updating the data differently. For example, some may only want to set the information at the time of authentication. Others may want to update on every request. Still others may want to update for a subset of requests (i.e. ignore static resources).

Yet providing your own metadata is very easy. A metadata provider consists of setting an attribute in session which is a single line of code. What do you have in mind that would make this easier? How often would you populate that data?
