### ISSUE TITLE
Client Side Sessions

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#234]
I have seen a few framework such as [ninja](http://www.ninjaframework.org/documentation/basic_concepts/sessions.html) storing sessions in user cookies. In our applications we are not heavily storing so much informations at sessions and using them rarely. It would be nice to have a client base session implementation.

**Comment by woutersamaey** [comment]
+1

**Comment by cemo** [comment]
@rwinch Any chance for 1.1?

**Comment by rwinch** [comment]
@cemo I am quite hesitant to add client side sessions. Generally speaking they are very difficult to get right and inertially less secure. For more information see the discussion on #186

To add to the above link. It seems odd that users want to shove their user information in a cookie. If you have a person service, would you try to encode the user's name in the person id so that you don't need to look up the name? If not, then why would you do that for a session (which is much more critical than the user's name).

With all that said, I'm still going to leave this issue open to see how much interest there is. However, at this point I don't see this making it into 1.1.

**Comment by rwinch** [comment]
Perhaps another alternative for this is to use [macaroons](http://macaroons.io/)

**Comment by vpavic** [comment]
Closing due to reasons explained in #768.
