### ISSUE TITLE
Include SecurityContext in SessionDestroyedEvent

### ISSUE THREAD

**Issue by natetyler** [spring-projects/spring-session#241]
It would be nice to include any SecurityContext instances which were associated with the destroyed session in the SessionDestroyedEvent, in order to bring it in line with `org.springframework.security.core.session.SessionDestroyedEvent`.

**Comment by rwinch** [comment]
@natetyler I agree. Unfortunately, this is quite difficult. The problem is that at the time Redis fires the event, the session is already gone. Furthermore, the event received from Redis does not contain the original information. This means there is no way to retrieve the SecurityContext.

For updates on this please track spring-projects/spring-session/issues/4

In the meantime, what are you trying to achieve with `org.springframework.security.core.session.SessionDestroyedEvent`?

**Comment by natetyler** [comment]
@rwinch I was looking through `org.springframework.session.data.redis.SessionMessageListener` and came to a similar conclusion. I am relying on the Session being destroyed to trigger some logout logic and it's crucial to know the username of the session that was destroyed. I've currently solved this by maintaining a separate map of sessionId to username in redis, but it seems unfortunate to do since that data is already in redis elsewhere.

**Comment by rwinch** [comment]
@natetyler I'm curious why you key off the username rather than the session id to cleanup the information. Without knowing details, it seems you might have issues if a user logged in twice. I'm also curious about your scenario so that I can make sure to account for it in future plans.

**Comment by natetyler** [comment]
We have our own concept of a session that we manage in the application tier, and this session is limited to one concurrent per user, even though that user may authenticate other HTTP sessions. When SessionDestroyedEvent is called, the "logout" code is only executed if the destroyed spring/http session is linked to our internal session.

I could key off of session id, in this case it doesn't matter as both username and session id are guaranteed to be unique - in light of the issue we are discussing I maintain an index for both so that it can be looked up by either value. 

Our scenario is probably not that different than many applications - just some record keeping around log in / log out.

**Comment by manderson23** [comment]
@natetyler @rwinch I'm facing a similar issue in that I want to trigger audit logging on session destroyed but I would like to get the username associated with the session ID.

I'm currently investigating how I can map this between login and logout. I'm using the MapSessionRepository rather than Redis.

One question I had for @rwinch is whether there would be any interest in adding SessionCreatedEvent since in my scenario the SecurityContext would then be available. However, there might be wider issues with this that I am overlooking.

**Comment by rwinch** [comment]
@manderson23 

I wonder if SessionCreatedEvent is very general purpose since most are probably looking for the user to be authenticated which may not happen when the session is created. Perhaps I am missing something?

**Comment by manderson23** [comment]
@rwinch I was assuming that the user was authenticated before the session was created but I guess that isn't the general case. 

Out of interested how would you see sessionCreated being handled if #4 was implemented? I guess that is similar in concept to what I was suggesting.

**Comment by rwinch** [comment]
@manderson23 I haven't really looked into the details of how it works within the servlet container. However, based on the description I wonder if at the time of creation all the attributes are empty since there would be no time to set an attribute at the exact moment of creation. In the end, I would expect this would work exactly as the servlet containers do (which I'm not certain of how that is at the moment).

**Comment by manderson23** [comment]
@rwinch OK thanks. Given that I'm going to be using MapSessionRepository + Hazelcast (or maybe Infinispan) in my final solution writing custom to support what I need isn't an issue.

**Comment by rwinch** [comment]
I'm closing this issue as a duplicate of #260 (which is a subset of #6).  Since I have resolved #260 this issue should be resolved. Also the concern about working with Spring Security's concurrency support should now be resolved. See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/#httpsession-httpsessionlistener for details

**Comment by gabber3000** [comment]
I too have the same problem. Are three days that I'm looking for a solution and I'm diventanto crazy. My method:
if(event instanceof SessionDestroyedEvent) {
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
always null
}
Do you have any solutions?

**Comment by rwinch** [comment]
Try the latest SNAPSHOT which resolves this.

NOTE: Accessing the SecurityContextHolder will not work because the session is expired (which means no SecurityContext will be found).

**Comment by gabber3000** [comment]
Thank you thank you really for your answer.
I'm using version 1.2.5 of Spring boot.
If I use the latest release version 1.3.0 of Sbrig Boot will solve my problem?
Thank you for your help.

**Comment by rwinch** [comment]
No. It is only fixed in the latest SNAPSHOT of Spring Session. You would need to override the version of Spring Session

**Comment by gabber3000** [comment]
OK perfect. Thank you so much for the help I could not find a solution :P

**Comment by gabber3000** [comment]
Hello
I have tried the latest spring session of SNAPSHOT version 1.0.3.
Unfortunately it does not work :( When I get the event SessionDestroyedEvent, I can only get the sessionId.
I also need to get the username of the authenticated user.
code:
@Service
public class SessionDestroyedListener   implements ApplicationListener<ApplicationEvent> {
	
	
	@Override
	public void onApplicationEvent(ApplicationEvent event) {
		// TODO Auto-generated method stub
	
		if(event instanceof SessionDestroyedEvent) {
	        SessionDestroyedEvent sdEvent = (SessionDestroyedEvent) event;  
	       
	       // String Username= <-----
	        String session = sdEvent.getSessionId();
	        System.out.println("Event :  "+session+ "   ");
	    }
	}

}

**Comment by rwinch** [comment]
@gabber3000 How are you trying to access the Authentication object? Also why are you trying to access it? You may not need to anymore.

**Comment by rwinch** [comment]
@gabber3000 Actually at this point, you should probably create a StackOverflow question with the spring-session tag. This will help others find answers too. You can post the question to here and I can answer it

**Comment by gabber3000** [comment]
the user can do the login with this code: 

@RequestMapping(value = "/login", method = RequestMethod.GET, produces = "application/json")
	
public com.domain.User login(Principal principal) {
	
	String token=RequestContextHolder.currentRequestAttributes().getSessionId();
		String nome=principal.getName();
		com.domain.User user=this.serviceUser.cercaUtente(nome);
		System.out.println("token:  "+token+ " Username:"+nome);
	    return user;
	}

I ask you that because my project needs to know the user name into session destroy, now I will find a solution, I save the session ID into my database so when arrive the session destroy event I can know the username. But I do not if that will be correct!
I had write about StackOverflow but nobody answer me!!
thank you

**Comment by rwinch** [comment]
> I had write about StackOverflow but nobody answer me!!

Link?

**Comment by gabber3000** [comment]
http://stackoverflow.com/questions/32118635/spring-boot-restfull-sessiondestroyedevent-get-userprincipal
