### ISSUE TITLE
How to force save/flush newly created HttpSession manually?

### ISSUE THREAD

**Issue by beku8** [spring-projects/spring-session#270]
I'm trying to achieve *zuul gateway* proxying *spring security form login* with shared session *spring session*. 

When /login page is requested for the first time, there's an inconsistent csrf token between gateway and the proxy login page appearing(Cookie csrf value & _csrf on the form does not match). 
The gateway does not yet save/flush the session before backend login page gets rendered, so the backend creates a new session, new csrf token value. I've checked it from a zuul filter(which gets executed before calling to the backend):
```repository.getSession(httpSession.getId()); //returns null```
The problem disappears from the 2nd request. I think this is because backend login can pick up the session from the redis via a ```SESSION``` cookie header, thus has a consistent csrf token.
If I can persist the current ```HttpSession``` to redis from the zuul filter, I assume the problem gets solved.

And a bonus question: Do you think its a bad idea to proxy login page? It will have Oauth2 logic & spring social login etc, thus I'm trying abstract it away in a separate "microservice".

**Comment by rwinch** [comment]
I'm having a hard time understanding your issue. Why does the gateway need the CSRF token? Can you put together a small sample that illustrates your issue?

**Comment by beku8** [comment]
I created a small demo here https://github.com/beku8/demo-gateway/

**Comment by beku8** [comment]
I actually managed a hacky way to [fix](https://github.com/beku8/demo-gateway/commit/372340aa5686f34a4d091e0a6dec7e5590053b4e)(```fix-1``` branch of demo app) the issue. Basically gateway sends the ```csrf``` token in a header if the ```redis session``` is null & backend login uses that token.
So I guess this issue probably does not belong to ```spring session```. 
I will try another approach csrf only on login not the gateway.
It seems like I'm hacking a lot just to get it work, could you give your opinion on my architecture?

**Comment by rwinch** [comment]
Right now there is no easy way to forcibly save the session since you do not have access to the Session object. This should change with #249. Once implemented #273 would ensure that if enabled you could ensure that as soon as an attribute was written it would be persisted immediately.

> And a bonus question: Do you think its a bad idea to proxy login page? It will have Oauth2 logic & spring social login etc, thus I'm trying abstract it away in a separate "microservice".

I'm not sure I would do it this way. I would probably make my front end a static site with no authorization built in. Then all my services (including login) would make JSON request/responses. The UI would update based upon those request responses.

NOTE: Removing Spring Security from the static site is not necessarily a good idea since it adds additional security benefits to just authorization. For example, it adds HTTP response headers that help protect your users.

**Comment by beku8** [comment]
ok thanks for the thorough answer, much appreciated
