### ISSUE TITLE
Persistent Implementation of the OidcSessionRegistry

### ISSUE THREAD

**Issue by nils-christian** [spring-projects/spring-session#2767]
Hi,

We are using OAuth2 with backchannel logout and would like to use spring-session. To support this, we would need a persistent implementation of the _OidcSessionRegistry_.

**Expected Behavior**

The _OidcBackChannelLogoutHandler_ should be able to map SIDs to the actual sessions even after a restart of the application.

**Current Behavior**

The _OidcBackChannelLogoutHandler_ uses an in-memory-implementation of the registry to map the SIDs from the indentity provider to the actual sessions so that it can perform the logout. This works fine, but breaks as soons as one restarts the application.

**Context**

Only solution so far is to implement a manual mapping between the SID and, for example, the principal name so that the entries can be removed manually from the _JdbcIndexedSessionRepository_.

**Comment by marcusdacoregio** [comment]
Thanks for the report, @nils-christian.

I'll have to check with @jzheaux how it should look like on Spring Session's side.

As a first measure, have you implemented your own `OidcSessionRegistry` and passed it to the DSL? What does it look like? If so, it should allow you to proceed while there is no built-in implementation.

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/issues/14511

The `OidcSessionRegistry` may sound similar to Spring Session implementations, but its job is different. Instead of managing client sessions like Spring Session does, its purpose is to link provider sessions with client sessions. Therefore, it doesn't fit into Spring Session, and implementations of that interface will be provided in Spring Security.
