### ISSUE TITLE
keyPrefix in SessionMessageListener is not same with in RedisOperationsSessionRepository

### ISSUE THREAD

**Issue by rainsoft** [spring-projects/spring-session#288]
In RedisOperationsSessionRepository, introduced the namespace for key prefix, but line 63 in SessionMessageListener is not adjust.

**Comment by rwinch** [comment]
@rainsoft Thanks for the report. This is somewhat intentional so we don't need to ensure the configuration for `SessionMessageListener` is in sync with `RedisOperationsSessionRepository`. Instead, Spring Session uses `RedisOperationsSessionRepository` as a listener so that all the configuration is self contained within `RedisOperationsSessionRepository`.

Perhaps that means we need to deprecate `SessionMessageListener`, but honestly I haven't thought about if it makes sense to keep it around or not.

Does this answer your question?

**Comment by rainsoft** [comment]
thanks for the answer.

**Comment by rwinch** [comment]
Closing in favor of #289
