### ISSUE TITLE
Use Spring Data Redis Index Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#301]
Instead of implementing an index on the username, we should leverage Spring Data Redis support [DATAREDIS-425](https://github.com/spring-projects/spring-data-redis/tree/issue/DATAREDIS-425) for this (once it is available).

Related #7

**Comment by vpavic** [comment]
I think this falls in the same category as #684 i.e. it doesn't fit our requirements due to similar reasons. Spring Data Redis secondary indexes are a feature of Redis Repositories and (like `HashMapper` API) doesn't fit our write scenarios where we maintain a delta of changes in order to optimize writes.
