### ISSUE TITLE
DefaultCookieSerializer drops domain at all if the pattern doesn't match

### ISSUE THREAD

**Issue by leonty** [spring-projects/spring-session#317]
This refers #299. 
If I use domainNamePattern to change the domain, the DefaultCookieSerializer removes the domain parameter at all if the regexp doesn't match. I came acros this when tried to implement "3rd level domain cookie" behavior. I used a regexp to keep to drop segments after 3rd and expected that domain that doesn't match the regexp at all just stay as is. (the regexp in the example of #299 is not very useful as it cuts the domain to 1 and 2 segments - imagine a cookie for ".org" !)

I think it would be more useful for real use to keep the domain unchanged if the regexp doesn't match return request.getServerName() at the end of the this code:

```
private String getDomainName(HttpServletRequest request) {
    if (domainName != null) {
        return domainName;
    }
    if (domainNamePattern != null) {
        Matcher matcher = domainNamePattern.matcher(request.getServerName());
        if (matcher.matches()) {
            return matcher.group(1);
        }
    }
    return null;
}
```

**Comment by leonty** [comment]
I've manged to get this with the regexp ^.*?(([\\w-]+\\.)?([\\w-]+\\.)?([\\w-]+))$ but still...

**Comment by rwinch** [comment]
Thanks for the report. I must be missing your point.  It is quite intentional that no domain is set if the regular expression does not match to ensure local development environments work well.  Can you perhaps spell out a concrete example of what is failing?

> I think it would be more useful for real use to keep the domain unchanged if the regexp doesn't match return request.getServerName() at the end of the this code:

I'm curious why you say this. From the JavaDoc of [Cookie.setDomain](https://docs.oracle.com/javaee/5/api/javax/servlet/http/Cookie.html#setDomain(java.lang.String))

> By default, cookies are only returned to the server that sent them.

This means that not setting the domainName property will result in the cookie being associated with the domain from `request.getServerName()`. It also reduces risk as we are not reflecting input into the response.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
