### ISSUE TITLE
Rename EnableGemFireHttpSession to EnableGemfireHttpSession

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-session#370]
Spring Data Gemfire's `@Enable…` annotation is named `@EnableGemfireRepositories`. For consistency, I propose that Spring Session's annotation be renamed from `@EnableGemFireHttpSession` to `@EnableGemfireHttpSession` (note the lower case `f`).

**Comment by rwinch** [comment]
Thoughts @jxblum ?

**Comment by jxblum** [comment]
Yeah... it is unfortunate that all the SDG class names containing "Gemfire" in the name have a lower case "f" when in fact the formal name for GemFire is with an upper case "F".  I am not partial either way.

**Comment by rwinch** [comment]
@wilkinsona I started looking into this. It seems that if we would rename `EnableGemFireHttpSession` to `EnableGemfireHttpSession` we would go through and rename everything from `GemFire*` to `Gemfire*`.

However, even this has inconsistencies. For example, if I rename `GemFireCacheTypeAwareRegionFactoryBean` to `GemfireCacheTypeAwareRegionFactoryBean` it is inconsistent with `com.gemstone.gemfire.cache.GemFireCache`.

This demonstrates that there are going to be inconsistencies either way. Further thought, I think it is Spring Data GemFire that is inconsistent with its naming conventions. I'd rather be consistent with the `com.gemstone.gemfire.*` naming conventions which uses `GemFire` rather than `Gemfire`.

For this reason I'm closing this as won't fix.

In the event, you want to view the changes (or you convince me that I am wrong), I have pushed a branch with the changes https://github.com/rwinch/spring-session/commit/c9902cc9c533d88a7559ec61d30fabe8f21b1051

**Comment by wilkinsona** [comment]
Thanks for the thorough investigation, @rwinch. Aligning with GemFire itself makes complete sense and I guess the ship has sailed on updating SDG to be consistent.

**Comment by jxblum** [comment]
@wilkinsona That is correct.  SDG's API is public and widely in use.  I wish I could have changed all name references in the API when I took over as the SDG lead to properly reflect the proper case in the "GemFire" name, but it is neither here nor there now.
