### ISSUE TITLE
Restructure Samples

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#384]
We should restructure the samples so they are easier to navigate. For example, we might do something like:
- Boot
  - Redis
    - httpsession
    - security
    - findbyusername
    - ...
  - GemFire
    - httpsession
    - security
    - findbyusername
    - ...
- Java
  - Redis
    - httpsession
    - security
    - findbyusername
    - ...
  - GemFire
    - httpsession
    - security
    - findbyusername
    - ...
- XML
  - Redis
    - httpsession
    - security
    - findbyusername
    - ...
  - GemFire
    - httpsession
    - security
    - findbyusername
    - ...

This won't add any missing guides for this new structure. However, it will encourage additional samples for the various permutations.

**Comment by vpavic** [comment]
Since there's quite a lot of duplicated code between the samples I wonder if something could be done about that too.

**Comment by jgrandja** [comment]
@vpavic For sure we will minimize code duplication or eliminate it all together if possible. The samples will be going through a major overhaul but it will be done in an iterative fashion. Thanks for the feedback!

**Comment by rwinch** [comment]
@vpavic Thanks for the feedback!

I'd like to try and keep all the code necessary for the samples in the sample rather than externalizing it. This does mean we have duplicated code. However, this also makes it easier for users trying out the sample to understand (which is the primary goal).

Perhaps we can create a Gradle task that keeps the source in sync or something like that?

**Comment by vpavic** [comment]
@rwinch, @jgrandja, I agree that complete elimination of duplicated code in the samples is highly unlikely, and I also agree that samples should be as simple as possible since they are supposed to be the starting point for new users.

What triggered me to make this comment is #454. A simple Boot sample project, fully consistent with other Boot based samples - nearly 8000 (!!) lines of code. I looked into it and saw that vast majority of that is in two Bootstrap CSS files. Maybe webjars or public CDN could be used for such resources?

**Comment by rwinch** [comment]
@vpavic I think webjars is a great idea! I created #457 to address this

**Comment by vpavic** [comment]
@rwinch agreed that webjars are better option.

BTW, I assume you've meant to reference #458?

**Comment by rwinch** [comment]
> BTW, I assume you've meant to reference #458?

Thanks! You are right. I updated my comment to make it easier for others to follow along.
