### ISSUE TITLE
Can provide an example of the integration of Spring-security-oauth2?

### ISSUE THREAD

**Issue by xiaolongyuan** [spring-projects/spring-session#465]

**Comment by 625096233** [comment]
there more problem integration spring-oauth2

**Comment by eleftherias** [comment]
Thanks for reaching out @xiaolongyuan.
We will not be providing an OAuth 2.0 sample because there is nothing different about the Spring Session configuration.
Some general OAuth 2.0 samples (without Spring Session) can be found in the Spring Security [samples](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2) example.
Feel free to reach out if you have specific issues integrating Spring Session.
