### ISSUE TITLE
MongoHttpSessionConfiguration should be public and expose setters for annotation attributes

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-session#489]
Similar than #488 but for Mongo. There is no way to reuse the configuration without using the annotation (this is the route that's chosen for Spring Boot).

**Comment by snicoll** [comment]
I think we need to reopen this one and fix the tests. We actually check that we can set the `collectionName` attribute on the configuration but we don't actually check it has an effect anywhere. Rather than checking the getter on the configuration (which is pretty useless IMO), we should validate that the created components avec the right state. 

In this case, the `collectionName` attribute isn't used anywhere. This problem already existed before this change.

**Comment by vpavic** [comment]
@snicoll I did some work on Mongo configuration tests after you reported this issue (since they were missing) to make them as consistent as possible with configuration tests for other stores.

I'll apply this to tests that were created in the PR that originally addressed this issue and will submit a new PR within few days.

**Comment by rwinch** [comment]
Sorry for the noise there (mistakenly had though this was associated to a released version). I went ahead and just reopened this to address https://github.com/spring-projects/spring-session/issues/489#issuecomment-213324391
