### ISSUE TITLE
RedisHttpSessionConfiguration being executed even though EnableRedisHttpSession is not set

### ISSUE THREAD

**Issue by jonhkr** [spring-projects/spring-session#498]
Hi,
I've been testing spring-session in my boot application and I noticed that even though EnableRedisHttpSession annotation is not set, a redis connection factory was being created.

The problem is that I don't want to have a redis server running when testing the application.

Here are some steps to reproduce this:
- Redis server must not be running
- Add both spring-boot-starter-redis:1.3.3.RELEASE and spring-session:1.1.1.RELEASE as dependencies of the project
- Remove any EnableAutoConfiguration and EnableRedisHttpSession from the configuration classes
- When the application is run, an exception will be thrown saying that it was not possible to connect to redis
- Remove the spring-session:1.1.1.RELEASE dependency
- Run the application again, it should run without complaining about any redis connection issues

**Comment by rwinch** [comment]
@jonhkr This is due to the Spring Boot `SessionAutoConfiguration` that is present in Spring Boot 1.3.0+ You can disable it by using `@SpringBootApplication(excludes = SessionAutoConfiguration.class)`. [In Spring Boot 1.4](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-session) (not yet GA) you can set `spring.session.store-type=none`.

**Comment by jonhkr** [comment]
@rwinch Great, thank you.
