### ISSUE TITLE
Sequential consistency problem?

### ISSUE THREAD

**Issue by TyronZerafa** [spring-projects/spring-session#508]
SessionRepositoryFilter is committing the session of a request twice:
1) first commit when the response is flushed (i.e., written to the client) through the `onResponseCommitted()` method in the `SessionRepositoryResponseWrapper`
2) second commit after the response is flushed in the final block of the `SessionRepositoryFilter` 

We encountered a use case that breaks sequential consistency when the **system is under heavy load**.
In our use case, we are performing two sequential requests; (1) first request reads a session attribute and then (2) a second request updates this same session attribute. We noticed that, sometimes, the second commit of the first request (after flushing the response) overwrites the commits performed by the second request (which was fired right after the first request returned). 

Is there any reason why sessions are committed twice to the repository?

**Comment by rwinch** [comment]
Thank you for the question! First what version of Spring Session and SessionRepository implementation are you using?

**Comment by TyronZerafa** [comment]
I'm using version 1.1.1.RELEASE of Spring-session.

I managed to replicate this issue both with the MapSessionRepository (i.e., with the distributed map of the Hazelcast-based repository) and the MongoSessionRepository whose implementation can be found [here](https://github.com/tmurakam/spring-session-mongodb/blob/master/spring-session-mongodb/src/main/java/org/tmurakam/spring/session/data/mongodb/MongoSessionRepository.java).

Hazelcast version 3.6.2

**Comment by rwinch** [comment]
We save at response committed because we need to ensure that as soon as the client has a reference to the session id (which can happen just after the response is committed). We save after the filter is done executing to ensure that if someone has made a change since the response was committed that the changes are persisted.

Some repository implementations are "smarter" than others. For example, the JDBC and Redis implementations both keep track of what has changed and only save the changes. This means that if only a single session attribute changes only that attribute is written. This also means if the save method is invoked more than once and nothing has changed nothing happens.

We should likely add similar enhancements for Mogno and the Map implementation. One down side is that with implementations like the Map implementation we can only write "all of the session" or nothing. This means if anything changes we have to write everything.

I created #525 and #526 to address this

**Comment by rwinch** [comment]
Closing since this should be taken care of via the referenced issues above. Please reopen if you disagree
