### ISSUE TITLE
I wonder session id application path

### ISSUE THREAD

**Issue by harbris** [spring-projects/spring-session#521]
I continue test multi war in one tomcat.

Set-Cookie: SESSION=63eb1ded-f7a6-49b8-b8c6-b2cbc2629ca8; Path=/v4/; HttpOnly

Set-Cookie: SESSION=8781966f-1da9-403a-bdff-18b142a2bbf7; Path=/v2/; HttpOnly

session-id is diffrent.

but original tomcat session id is same in this situation.

I already read some issues related this situation.

and I wonder when this situation fixed.

**Comment by rwinch** [comment]
By default the cookie path is the context root. In order to share the session across multiple applications, you need to specify the cookie path to a path that would be shared between the applications. For details on how that might be done, you can refer to http://docs.spring.io/spring-session/docs/current/reference/html5/guides/custom-cookie.html

**Comment by rwinch** [comment]
I believe this is answered now. If you have follow up questions, feel free to reopen
