### ISSUE TITLE
Using a custom Session Alias parameter causes CSRF-token check to fail

### ISSUE THREAD

**Issue by robin-maxxton** [spring-projects/spring-session#532]
Hi,

I having some trouble with using Spring Session in combination with Spring Security OAuth2 and JWT.
My main goal is to have a query parameter, in this case "custom", to hold the session alias.
This query parameter is already used to select certain settings on each request for the authentication process.
So the calls will look like this:
```
// Session 'one'
<OAuth2 provider>/uaa/oauth/authorize?client_id=client&response_type=token&redirect_uri=/&custom=one
// Session 'two'
<OAuth2 provider>/uaa/oauth/authorize?client_id=client&response_type=token&redirect_uri=/&custom=two
```

The problem I'm facing is that the CRSF-token mechanism breaks when I use this custom alias.
On posting the login form you'll be presented with an error, e.g.
`Invalid CSRF Token '6c4a7b8e-20dd-4cf2-9ad5-58ac83dfd5d3' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.`
When using the default parameter "_s" the CRSF token works fine.

That brings me to the second problem which I'll hit when the error with the CSRF-token is resolved.
When I use the default parameter, only one session is allowed to authenticate. For example if I call 
<OAuth2 provider>/uaa/oauth/authorize?client_id=client&response_type=token&redirect_uri=/&_s=1
I'm able to generate a token for alias '1', but if I change it to '0' I get an access denied error.
The other way around it results in the same error ('0' first, then '1').

In both cases I think the problem lies in the configuration for HTTP in the AuthorizationSecurityConfig class.
But I'm not sure.
To make things easier I made a sample project which reproduces the problem.
https://github.com/robin-maxxton/session-oauth2-sample

Thanks in advance.
Robin

**Comment by jgrandja** [comment]
Hi @robin-maxxton. I've taken a look at your code and configuration and it all looks good. However, there are a couple of minor things you missed in your html templates.

In your _login.html_ template you need to pass the **session alias** as a hidden form field in your login form, like this:

```
	<form role="form" th:action="@{/login}" method="post">
		...
		<input type="hidden" name="custom" th:value="${param.custom[0]}" th:unless="${param.custom == null}" />
		...
	</form>
```

The reason the CSRF token was not found in the session when the login form was posted is because the CSRF token was saved in _**session alias one**_ but when you posted the login form without the session alias parameter it would default to _**session alias 0**_ (which is the [default session in Spring Session](http://docs.spring.io/spring-session/docs/1.2.0.RELEASE/reference/html5/#httpsession-multi)). 

FYI, the session cookie that is written on the response when _**session alias one**_ is created looks like this:

`Cookie:SESSION="0 70f275a8-5dd7-4c3f-bdf3-f04a62944a7a one ab8ef9ac-0cea-4c8f-8984-87ec9dd1916c"`

So you just need to be sure you are passing the _**session alias**_ in all requests including POSTS.

Another thing to point out is that you do not need to explicitly set the CSRF as a hidden form field, as you have:

`<input type="hidden" id="csrf_token" th:name="${_csrf.parameterName}" th:value="${_csrf.token}"/>`

Spring Security integrates with Thymeleaf using [RequestDataValueProcessor](http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html#integration-with-requestdatavalueprocessor). Notice the login form is using Thymeleaf specific action attribute:

`th:action="@{/login}`

Using this attribute will automatically write hidden form fields into the form, specifically the CSRF token. View the page source when the login form renders to verify.

As far as your second issue goes...

> When I use the default parameter, only one session is allowed to authenticate. For example if I call 
> /uaa/oauth/authorize?client_id=client&response_type=token&redirect_uri=/&_s=1
> I'm able to generate a token for alias '1', but if I change it to '0' I get an access denied error.
> The other way around it results in the same error ('0' first, then '1').
> 

Because the `Authentication` is stored in the `HttpSession` (backed by Redis in your setup), you are required to authenticate for each of the session alias' you use, so one and two in your case.

So for example, when you issue the following request:

`/uaa/oauth/authorize?client_id=client&response_type=token&redirect_uri=/&_custom=one`
this will trigger the Authentication flow for _**session alias one**_. After successful authentication you will receive your token.

Then when you issue the following request:

`/uaa/oauth/authorize?client_id=client&response_type=token&redirect_uri=/&_custom=two`
this will trigger the Authentication flow for _**session alias two**_. After successful authentication you will receive your token.

I made the changes to your code and tested this all out. I tried pushing to your repo but don't have permissions. I'll attach the 2 files that changed so just replace and give it a go.
Let me know if you have any questions.



[templates.zip](https://github.com/spring-projects/spring-session/files/286873/templates.zip)

**Comment by jgrandja** [comment]
Was talking to @rwinch today and he mentioned there is no need to explicitly add the **_session alias_** as a hidden form parameter as in the previous post:

```
<input type="hidden" name="custom" th:value="${param.custom[0]}" th:unless="${param.custom == null}" />
```

You can remove that altogether and provide this configuration in your `AuthorizationSecurityConfig` instead:

```
http.exceptionHandling().authenticationEntryPoint(
       ....
            .sessionManagement()
                .enableSessionUrlRewriting(true)
                ....
```

With this configuration, the **_session alias_** will automatically be added as a request parameter to all url's, including the form action attribute.

One other very important thing to update in your build.gradle is your [Spring Session Dependencies](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot.html#updating-dependencies).

Update to:

```
compile("org.springframework.boot:spring-boot-starter-redis:${spring_boot_version}")
compile("org.springframework.session:spring-session:1.2.0.RELEASE")
```

**Comment by robin-maxxton** [comment]
Hi @jgrandja.

Thanks for the detailed solution. I tried it out and it works great. I spent some time reading your answer, which does a great job on further explaining the mechanism behind Spring Session, to get a better understanding on what's going behind the scenes.

Now that the the application started working I really like the fact that the sessions remain valid if the provider gets restarted. This is functionality I initially did't think about, but is more than welcome.

I've seen some people asking for an example project with Spring OAuth2 and Spring Session. I updated my sample project with the changed so that other people may get some use out of it.
