### ISSUE TITLE
JdbcOperationsSessionRepository does not respect per Session expiration times

### ISSUE THREAD

**Issue by cooolwire** [spring-projects/spring-session#580]
I am using Spring Session v1.2.1 with Postgres. The sessions are persisted into my Postgres database using the `JdbcOperationsSessionRepository`.

The default inactive time that I am using for my sessions is 30 days. Once a user logs in, I do `request.getSession().setMaxInactiveInterval()` and change it to 180 days.

However for some reason the 180 days is not being respected and sessions keep getting deleted every hour. For example:

![](https://dl.dropboxusercontent.com/spa/urudiofz4a6071b/dcvg193z.png)

This session should have lasted 180 days but it got deleted as soon as the next hour started.

Does anyone know how I can stop these sessions from getting deleted and have them stick around for 180 days?

I am guessing [this function](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L464) has something to do with this.

Here's the part of my application that extends the user's max inactive interval:

```
private void setupSession(HttpServletRequest request, User user) {
   HttpSession session = request.getSession();
   session.setMaxInactiveInterval(15552000);
   session.setAttribute("user-id", user.id);
}
```

**Comment by vpavic** [comment]
@cooolwire Thanks for the report.

I have confirmed your finding with a test case and indeed this seems to be a problem in ```JdbcOperationsSessionRepository#cleanUpExpiredSessions```.

Calculation of valid last access time only considers the value of ```JdbcOperationsSessionRepository```s global ```defaultMaxInactiveInterval``` when deleting expired sessions, instead of max inactive interval of an individual session. I'll look into the possible solutions for this.

**Comment by vpavic** [comment]
At first glance solving this problem seemed as easy as reducing `cleanUpExpiredSessions` operation to the following SQL statement:

```sql
DELETE FROM %TABLE_NAME%
WHERE LAST_ACCESS_TIME < ? - MAX_INACTIVE_INTERVAL * 1000
```

However this fails with some in-memory RDBMSs (namely H2 and Derby) since they are unable to perform an implicit cast on expression in `WHERE` clause.

Other vendors I've tested against (PostgreSQL, Oracle and MySQL/MariaDB) worked without any problems.

**Comment by vpavic** [comment]
The solution described above is available in [my fork](https://github.com/vpavic/spring-session/tree/gh-580).

However this fails integration tests, which are based on H2, due to limitation also described in previous comment. I've reported the [issue against H2](https://groups.google.com/forum/#!topic/h2-database/ND-UYrsMBSk).

**Comment by vpavic** [comment]
I've also opened [DERBY-6902](https://issues.apache.org/jira/browse/DERBY-6902).

H2 issue doesn't seem to be addressed anytime soon. So I guess we'll need to provide an option to customize SQL statements. Thoughts @rwinch?
