### ISSUE TITLE
When using multiple instances, also schedule multiple runs.

### ISSUE THREAD

**Issue by kwyi** [spring-projects/spring-session#581]
When using multiple instances, also schedule multiple runs.

https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java

        @Scheduled(cron = "0 * * * * *")
	public void cleanUpExpiredSessions()

Do not have a problem?
Going to create a method for controlling the operation?

**Comment by vpavic** [comment]
Hi @kwyi - is there a particular problem you are experiencing with the clean up operation? If so, can you describe it in more detail?

If you are worried about that the `cleanUpExpiredSessions` potentially executes concurrently on multiple application instances, there shouldn't be any problems with that since this method only deletes the sessions that matches a certain criteria.
