### ISSUE TITLE
Keep session after close browser

### ISSUE THREAD

**Issue by maxiplay** [spring-projects/spring-session#593]
Hi,

How can you keep session after the user close his browser ? 

When I close a tab the session is kept but no when I close et reopen the browser.

I used spring-boot-starter-parent 1.4.0.RELEASE. I tried with the gs-securing-web example of Dave Sayer combined with 

`@EnableRedisHttpSession, `

```
 @Bean
    public JedisConnectionFactory connectionFactory() {
            return new JedisConnectionFactory(); 
    }
```

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session</artifactId>
		</dependency>
```

**Comment by rwinch** [comment]
@maxiplay This is because by default the session cookie is specified as a [session cookie](https://en.wikipedia.org/wiki/HTTP_cookie#Session_cookie)

If you want to specify the cookie expiration, you can do so using the instructions found in the [Custom Cookies Guide](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/custom-cookie.html).

Keep in mind the cookie is only written once. This means the cookie expiration is not updated with user activity (as the session expiration is). For example, if you set the expiration of the cookie to be 30 minutes, the user will need to authenticate again in 30 minutes even if they are actively using the application.

**Comment by maxiplay** [comment]
OK thank you :)

**Comment by rohitkrishna094** [comment]
@rwinch Sorry for disturbing, but this Custom Cookies Guide link is broken. It points to this now 
https://docs.spring.io/spring-session/docs/current/reference/html5/guides/custom-cookie.html which is broken. Do you happen to know the latest url? If not, thats fine. Have a good day.

**Comment by eleftherias** [comment]
@rohitkrishna094 This is the current guide for configuring custom cookies.
https://docs.spring.io/spring-session/docs/current/reference/html5/guides/java-custom-cookie.html
