### ISSUE TITLE
Use the Native Redis Support for mapping the RedisSession

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#684]
We should switch to using the Native Redis Support for mapping the RedisSession rather than manually managing this on our own.

NOTE: I think this is a duplicate, but I wanted to write this down so we don't forget

**Comment by vpavic** [comment]
I took a closer look at this as a part of #862 and the conclusion is that Spring Data Redis `HashMapper` doesn't fit us due to following reasons:
- for write scenarios we maintain a delta (to optimize writes) which itself is basically a hash so there's nothing to map there
- for read scenario the `HashMapper` API doesn't provide the access to the key so we would have to store it as a hash attribute which is an overhead
