### ISSUE TITLE
spring-session-data-redis   session保存对象  redisTemplate获取对象

### ISSUE THREAD

**Issue by lexang** [spring-projects/spring-session#690]
`	
			 HttpSession session = request.getSession();
			 String id=session.getId();
			 System.out.println("session  id  :"+id);
			 
			 
			 String value = (String) session.getAttribute("username&&redis");
			 System.out.println("username&&redis"+value);
			 
			 
			User user= userService.getByLogincode(userName);
			
			 session.setAttribute("user", user); 
			 user =(User) session.getAttribute("user"); 
			 
			 System.out.println( redisTemplate.opsForHash().get("spring:session:sessions:"+id, "sessionAttr:user"));
			 System.out.println(redisTemplate.boundHashOps("spring:session:sessions:"+id).get("sessionAttr:username&&redis"));
			 Map map=redisClient.hgetall("spring:session:sessions:"+id);
			 
			 
			 System.out.println(redisTemplate.boundHashOps("spring:session:sessions:"+id).entries());
			 
			  user=(User) redisTemplate.opsForHash().get("spring:session:sessions:"+id, "sessionAttr:user");
			 
			  System.out.println(user);`

![qq 20161211144200](https://cloud.githubusercontent.com/assets/10265864/21078603/38184152-bfb0-11e6-9633-8381097f212a.png)
![qq 20161211144255](https://cloud.githubusercontent.com/assets/10265864/21078604/381ca4ea-bfb0-11e6-9ffb-d509c1224d1e.png)

从reedis获取的属性 为空 不是同一个对象 怎么解决？

**Comment by panchenko** [comment]
@lexang Seems like this question is related to org.springframework.session.data.redis.RedisFlushMode.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
