### ISSUE TITLE
Add support for querying session's by a specific user identifier

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#7]
In some situations it may be nice to be able to query sessions by a user identifier (i.e. a username). This would be useful for displaying all the active sessions of a particular user.

**Comment by paranoiabla** [comment]
+1

**Comment by shanewow** [comment]
Hi, I would like to create a wrapper or extend the RedisOperationsSessionRepository in order to save each session to a second RedisTemplate using the username instead of sessionId as the hash. I hit a brick wall with trying to call or override the save method as RedisSession is private. Can this class be made public? Or is there another way to filter/inject logic when the session is created and deleted? Essentially how would I delete and create from a second RedisTemplate at the same time the RedisOperationsSessionRepository does? Thanks.

**Comment by rwinch** [comment]
@shanewow Right now I'm not sure there is a good answer as to how to do that. We'd really like to keep the `RedisSession` private so that we can modify it as necessary without causing users any passivity issues.

The best solution I can come up with is to ensure that the username is populated in the session attributes. Then, anytime the `HttpServletRequest.getUserPrincipal()` changes ensure to save using another RedisTemplate a mapping of the username to the session id (which might contain multiple ids). This could all be done in a separate `Filter` and interacting with the generic `HttpSession` and `HttpServletRequest` API's.

The problem is to figure out how to clean up expired sessions from the username. I'm not quite sure how to properly go about this.

**Comment by rwinch** [comment]
This is now supported with the Redis implementation. See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/findbyusername.html (will be deployed in next 30 min or so). Also see http://spring-session-kill.cfapps.io/ for the deployed sample.

**Comment by praptin** [comment]
+1
