### ISSUE TITLE
SESSION_ATTRIBUTES is not removed when SESSION is removed when using JdbcHttpSessionConfiguration

### ISSUE THREAD

**Issue by Sankozi** [spring-projects/spring-session#731]
I am using JdbcHttpSessionConfiguration from Spring Session 1.3.0. My system has lots of very short sessions and noticed that `SESSION_ATTRIBUTES `table is getting big very quickly while `SESSION `table is usually small. 

After bit of investigation I've noticed that `JdbcHttpSessionConfiguration `creates `JdbcOperationsSessionRepository` that has `cleanUpExpiredSessions` method that only deletes records from `SESSION` table. It should also remove orphaned `SESSION_ATTRIBUTES` records with something like this 
```
delete sa
from session_attributes sa
where not exists (select 1 from session s where s.SESSION_ID = sa.SESSION_ID)  
```
(script probably cannot be used in all supported databases)

**Comment by vpavic** [comment]
@Sankozi, thanks for the report - can you please provide more details about your database? Specifically, what RDBMS are you using, and did you use schema scripts provided by Spring Session to create required the required tables?

Regarding the session deletion, `SPRING_SESSION_ATTRIBUTES` table has a foreign key that references `SPRING_SESSION` with cascade on delete operation. This should ensure that deletes to parent (session) are cascaded to child (attributes) records. If there was a foreign key without cascade on delete, then the delete on parent would fail due to referential integrity, therefore I suspect you're missing this constraint.

**Comment by Sankozi** [comment]
@vpavic Thanks for help. It was my mistake - I used JdbcHttpSessionConfiguration#setTableName so I had to recreate script and did it badly.
