### ISSUE TITLE
Configuration of Backups in Hazelcast

### ISSUE THREAD

**Issue by hotstepper13** [spring-projects/spring-session#788]
We have setup a Hazelcast Cluster with 3 nodes and 2 (spring-boot) Applications (each with also 3 nodes) that are exchange session data with the hazelcast cluster.

We have seen that the applications stop working correctly if we redeploy the hazelcast cluster which was traced down as incomplete dataset. During research we have seen #524 which seems to address a similar issue. As ReplicatedMap in Hazelcast is still considered as "problematic", the other way (the hazelcast way) is to configure backups for a Map.

From what I could see we creating the Map by Annotation so there is only the option to set a name and inactivity timeout. I have not found an option how we could adjust the "backup" configuration of the map that is used. 

A backup of n would mean that for each partition at least n backup´s are present in the cluster. So a cluster of 3 nodes can hold 2 backups. If one (hazelcast) node goes down, another (hazelcast) node is capable of serving the map without loss of data.

For me it looks like that the default implementation has a backup count of zero. Therefore it could be a change request to add an config option for this. Otherwise, please show me how we could change that configuration.

**Comment by rwinch** [comment]
Thanks for the report

@vpavic Can you take a look at this one please?

**Comment by vpavic** [comment]
@hotstepper13 Spring Session does not actually do any configuration of Hazelcast Map that is used to store the sessions. We only obtain the `IMap` with name defined in `EnableHazelcastHttpSession#sessionMapName` - this can be seen in [HazelcastHttpSessionConfiguration](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/hazelcast/config/annotation/web/http/HazelcastHttpSessionConfiguration.java#L62-L65). Also note that `EnableHazelcastHttpSession#maxInactiveIntervalInSeconds` actually operates on the session itself rather than on `IMap` config.

We do however provide support and samples for users to configure Hazelcast Map in order to support features such as `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue` - see the [HttpSession with Hazelcast](http://docs.spring.io/spring-session/docs/1.3.1.RELEASE/reference/html5/#httpsession-hazelcast) section of the reference manual. Note that the Map configuration was obtained from the Hazelcast `Config` by the name used in Spring Session configuration (`spring:session:sessions` is the default value).

So as in the `ValueExtractor` example from above, you should use standard Hazelcast configuration mechanism to configure the desired backup levels.

**Comment by hotstepper13** [comment]
Thanks for the information. I am a little bit curios right now. The configuration for the map backup (http://docs.hazelcast.org/docs/3.5/manual/html/map-backups.html) does it have to be created within the application or within the server? I am using the hazelcast kubernetes bootstrapper to start a cluster of 3 nodes. I talked to one of our DEVs and he ment that this is nothing that can be done on application side. From my perspective, the map to store the session information will be created by the application and therefore it has to hold the configuration for backups.

**Comment by vpavic** [comment]
The configuration of Hazelcast Maps, or any of the other Hazelcast's distributed objects, is done on the server.

Since Hazelcast can be used in either client-server or embedded topology, the configuration of Hazelcast instance in an embedded topology might be misleading you into direction of thinking that Map is configured by the consumer.

The links from my previous [comment](https://github.com/spring-projects/spring-session/issues/788#issuecomment-303414618) explain how the configuration of Hazelcast is done from Spring Session's perspective. On top of that you can also take a look at our [Hazelcast Javaconfig sample](https://github.com/spring-projects/spring-session/tree/master/samples/javaconfig/hazelcast) which basically demonstrates the same thing.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
