### ISSUE TITLE
Consider for a more flexible configuration of the Redis Namespace parameter.

### ISSUE THREAD

**Issue by tggm** [spring-projects/spring-session#818]
Currently the only way to configure the Redis namespace is through the @EnableRedisHttpSession annotation or via a system property. Both these options are defined at compile time and unchangeable. 

We would like to be able to set this parameter depending on the environment: ie: namespace-dev, namespace-qa, namespace-prod, etc... using our own beans (with a @PropertySource, for example) which is currently impossible since there is no way to override the internal RedisSession configuration mechanism.

Motivation for this request: We centralize the environment configuration on a global configuration bean using @Resource annotations to read those values from JNDI, thus delegating to the container all the environment specific configuration. 

Since the Redis namespace might be different across environments (Dev, QA, Production) it should be flexible enough to be configured via the container (or some other mechanism), on application startup.

Thank you.

**Comment by vpavic** [comment]
Hi @tggm - can you clarify why do you think configuring Redis namespace via system property is _defined at compile time and unchangeable_? Actually the point of having it exposed as system property is to make it externally modifiable.

In addition to that, do you by any chance use Spring Boot? If so, note that Boot has a first-class [support for Spring Session](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-session), which also exposes `@EnableRedisHttpSession` attributes as configuration properties.

If you don't use Boot you could take a look at its [`RedisSessionConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/RedisSessionConfiguration.java) for an inspiration to apply the similar approach in your app.

**Comment by tggm** [comment]
Hello @vpavic.

I delegate to the Application Server all the properties used to configure the application. For example: connection strings, configuration properties (like webservice URL's, email addresses, etc...) are all obtained via JNDI.

This strategy allows the developer to deploy the same application in Development, QA or Production environments without having to change .properties files. I don't believe in setting environment specific applications in .properties files as it's done by Spring Boot. Nor do I believe in changing properties files using Maven tricks. These things are environment specific and so should be defined by the Application Server (Tomcat, JBoss, etc...).

Right now I can configure all the properties via JNDI (with spring resource annotations) except this Redis Namespace. As I said it is defined in the EnableRedisHttpSession (at compile time) and you cannot set it during application startup.

Yes, I am using Spring Boot.

Thank you.

**Comment by vpavic** [comment]
@tggm Well the system property for configuring Redis namespace meets your requirement, doesn't it? If you're deploying your application to, for instance, with Tomcat you'd set the following in `setenv.sh` (see the reference [here](https://tomcat.apache.org/tomcat-8.5-doc/RUNNING.txt)) script:

```bash
#! /bin/sh
export CATALINA_OPTS="$CATALINA_OPTS -Dspring.session.redis.namespace=mynamespace"
```

In this case you of course don't set the `redisNamespace` attribute of `@EnableRedisHttpSession`.

> I don't believe in setting environment specific applications in .properties files as it's done by Spring Boot. Nor do I believe in changing properties files using Maven tricks. These things are environment specific and so should be defined by the Application Server (Tomcat, JBoss, etc...).

It seems you're under impression that Spring Boot only allows configuring application properties using traditional `.properties` file. I'd recommend you to take a closer look at [Externalized Configuration chapter](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) of Boot's reference manual - you'll find out that it supports having environment defined configuration.

Speaking of Boot and its already mentioned first-class [support for Spring Session](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-session), I'd suggest to get familiar with that as well, as you don't need to use `@EnableRedisHttpSession` since Boot can take care of setting up Spring Session for you with only two configuration properties:

```properties
spring.session.store-type=redis
spring.session.redis.namespace=mynamespace
```

As explained above, you can easily set those using within your environment.

If all of that doesn't suit you, instead of using `@EnableRedisHttpSession` you can also extend our `RedisHttpSessionConfiguration` and bind it to your configuration sources, since the `RedisHttpSessionConfiguration` exposes setters for the relevant properties (that's why I suggested in the previous comment that you could take a look at Boot's [`RedisSessionConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/RedisSessionConfiguration.java)).

**Comment by tggm** [comment]
ok, thanks.
