### ISSUE TITLE
When session is invalid , can't able to get SavedRequest. Instead its creating new session for me . 

### ISSUE THREAD

**Issue by firozaleph** [spring-projects/spring-session#837]
I am working on Masterpass integration.

Masterpass calls Logout function to clear old cookies asynchronously .How do we handle that in Logout call.?
Logout (asynchronously, which means will be processed faster and update new session to other threads ) and Checkout call( which need to be saved as saved Request ) will be triggered sequence . 

My question is how do we asynchronously logout and assign new session to next Checkout call. So that Checkout request can be saved in session.

**Comment by vpavic** [comment]
Hi @firozaleph, could you please clarify the relation of your question to Spring Session?

Since you're mentioning `SavedRequest` (I assume this is Spring Security's `org.springframework.security.web.savedrequest.SavedRequest`) and logout and nothing in your use case sounds specific to Spring Session, this might be better suited for Spring Security tag at Stack Overflow?

**Comment by firozaleph** [comment]
Yes this is suited for session. 

My question here is "How can we accomodate spring security session logout asynchronously"?

when **hosturl/contextPath/Logout** is hit asynchronously, i want to do Logout functionality asynchronously.

**Comment by vpavic** [comment]
@firozaleph Can you provide a minimal sample that demonstrates the problem with your use case?

Obviously your flow involves Spring Security's logout and interacts with `HttpSession` but the relation to the [Spring Session](http://projects.spring.io/spring-session/) project is still unclear to me.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
