### ISSUE TITLE
2.0.0.M3 not in Spring Milestones maven repo

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-session#840]
According to https://spring.io/blog/2017/07/25/spring-session-2-0-m3-released Spring Session 2.0.0.M3 has been released. http://projects.spring.io/spring-session/ indicates it should be available at https://repo.spring.io/libs-milestone/org/springframework/session/spring-session/2.0.0.M3/ but there are no artifacts present.

Can you please publish Spring Session 2.0.0.M3 to the Spring milestones Maven repository?

**Comment by vpavic** [comment]
Hi @candrews - the `2.0.0.M3` actually is in the [milestones repo](https://repo.spring.io/libs-milestone/org/springframework/session/spring-session-core/) however we have changed the project's module structure so the `spring-session` artifact (which used to contain all the Spring Session code) doesn't exist anymore and is replace by `spring-session-core`. Other artifacts (`spring-session-data-redis`, `spring-session-hazelcast` and `spring-session-jdbc`) exists however instead of being dependency aggregator modules they now contain all the code related to given data store.

For more background on this change see #768 and [this blog post](https://spring.io/blog/2017/05/11/spring-session-2-0-0-m1-released).

**Comment by candrews** [comment]
I hadn't noticed those announcements - thank you for pointing out this change. My apologies for the erroneous bug report
