### ISSUE TITLE
JdbcOperationsSessionRepository fails when inserting in db2

### ISSUE THREAD

**Issue by diegolovison** [spring-projects/spring-session#882]
Using spring-session-jdbc with db2 it is failing when inserting the data in SPRING_SESSION table.

`
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT INTO SPRING_SESSION(SESSION_ID, CREATION_TIME, LAST_ACCESS_TIME, MAX_INACTIVE_INTERVAL, PRINCIPAL_NAME) VALUES (?, ?, ?, ?, ?)]; Assignment of a NULL value to a NOT NULL column "TBSPACEID=2, TABLEID=26636, COLNO=0" is not allowed.. SQLCODE=-407, SQLSTATE=23502, DRIVER=4.16.53; nested exception is com.ibm.db2.jcc.am.SqlIntegrityConstraintViolationException: Assignment of a NULL value to a NOT NULL column "TBSPACEID=2, TABLEID=26636, COLNO=0" is not allowed.. SQLCODE=-407, SQLSTATE=23502, DRIVER=4.16.53`

Executing the following query in db2:

```
SELECT C.TABSCHEMA, C.TABNAME,
  C.COLNAME
FROM SYSCAT.TABLES AS T,
  SYSCAT.COLUMNS AS C
WHERE T.TBSPACEID = 2
      AND T.TABLEID = 26636
      AND C.COLNO = 0
      AND C.TABSCHEMA = T.TABSCHEMA
      AND C.TABNAME = T.TABNAME
```

It will return:

TABSCHEMA=MY_SCHEMA
TABNAME=SPRING_SESSION
COLNAME=PRIMARY_ID

**Comment by vpavic** [comment]
Hi @diegolovison, thanks for the report.

Can you provide more info about the problem? The `JdbcOperationsSessionRepository.PrincipalNameResolver#resolvePrincipal` returning `null` shouldn't cause insert statement to fail since `principal_name` column is nullable. Can you also clarify a bit your OAuth2 scenario, I assume this is an OAuth2 client application we talking about? A sample app to reproduce the problem would be ideal.

**Comment by diegolovison** [comment]
Thank you for your valuable feedback. I will provide more information soon.

**Comment by vpavic** [comment]
@diegolovison Thanks for the update. One note though - please use a new comment to add information to the issue, since we don't get the notification if you update the existing comment. Thanks.

Some vital information is still missing - which version of Spring Session do you use? It seems the you are using Spring Session 1.3 but that you've applied schema script from `master` branch (which is 2.0).

**Comment by diegolovison** [comment]
Thank you for you feedback.
You are right. Just started using the sql shipped with the jar and the things started working.

Cheers

**Comment by vpavic** [comment]
Thanks for letting us know.
