### ISSUE TITLE
Problems with SpringSecurity, UserDetails custom implementation and SpringSession

### ISSUE THREAD

**Issue by OArtyomov** [spring-projects/spring-session#915]
1. We use spring-session-jdbc 1.3.1.RELEASE. AppUserDetails is our custom implementation of UserDetails interface

   2. Controller method  
  ```
  @RequestMapping(value = CHANGE_BIZ, method = GET)
    public String changeActiveBiz(@RequestParam(name = "id") int bizId,
                                  @AuthenticationPrincipal AppUserDetails userDetails,
                                  HttpServletResponse response, HttpSession httpSession) {
        BizEntity biz = userService.hasBiz(userProvider.getSessionUser(), bizId);
        if (biz != null) {
            userDetails.setActiveBizId(biz.getId());
            response.addCookie(new Cookie(AppUserDetails.ACTIVE_BIZ_COOKIE, Integer.toString(biz.getId())));
            Object securityContext = httpSession.getAttribute("SPRING_SECURITY_CONTEXT");
            if (securityContext != null){
                httpSession.setAttribute("SPRING_SECURITY_CONTEXT", securityContext);
            }
        }

        return REDIRECT_URL_PREFIX + MY_DASHBOARD;
    }  	
	```
	3. I have to add code to reset attribute to session, because it does not work in other case.
	4. Root cause in calculation delta in class JdbcSession. I think, it should use other way.

**Comment by OArtyomov** [comment]
1. We use spring-session-jdbc 1.3.1.RELEASE. AppUserDetails is our custom implementation of UserDetails interface

   2. Controller method  
  {code}
  @RequestMapping(value = CHANGE_BIZ, method = GET)
    public String changeActiveBiz(@RequestParam(name = "id") int bizId,
                                  @AuthenticationPrincipal AppUserDetails userDetails,
                                  HttpServletResponse response, HttpSession httpSession) {
        BizEntity biz = userService.hasBiz(userProvider.getSessionUser(), bizId);
        if (biz != null) {
            userDetails.setActiveBizId(biz.getId());
            response.addCookie(new Cookie(AppUserDetails.ACTIVE_BIZ_COOKIE, Integer.toString(biz.getId())));
            Object securityContext = httpSession.getAttribute("SPRING_SECURITY_CONTEXT");
            if (securityContext != null){
                httpSession.setAttribute("SPRING_SECURITY_CONTEXT", securityContext);
            }
        }

        return REDIRECT_URL_PREFIX + MY_DASHBOARD;
    }  	
	{code}
	
	3. I have to add code to reset attribute to session, because it does not work in other case.
	4. Root cause in calculation delta in class JdbcSession. I think, it should use other way.

**Comment by vpavic** [comment]
@OArtyomov I'm not sure I fully understand the problem you are reporting. Could you please try to describe the behavior you're seeing vs the one you're expecting? A sample app that reproduces this problem would be very helpful as well.

**Comment by OArtyomov** [comment]
Here is example:  https://github.com/OArtyomov/spring-session-jdbc-example
   
Compare methods UserController.changeExternalId and UserController.changeExternalIdAndSaveToSession   

I have to notifiy HttpSession that Spring Security context has changed. In my opinion, method UserController.notifySessionChange is excess.

**Comment by vpavic** [comment]
Thanks for the sample @OArtyomov.

The background of your problem is actually the same to another issue that was reported recently - see #921. You're basically updating session's attribute (which in this case is the `SecurityContext`) without notifying the session of the change (you do that, however, in `UserController#notifySessionChange`).

As explained in #921 (and other issues reference in that one), since Spring Session uses an external session store, the session object you're interacting with is a copy retrieved from the session store. This is in contrast to the situation with container's default session store that is typically _in-memory_, which means you're interacting with the same `HttpSession` instance (rather than a copy) that represents a given session.

IMO you should move your logic that modifies principal (in `AppUserDetails#setExternalId`) to a `Filter` that would be a part of Spring Security's filter chain, and do the modification of principal in a way that takes into consideration the behavior explained above.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
