### ISSUE TITLE
Redis not updating JAVA Objects modified in a request without set being called

### ISSUE THREAD

**Issue by shankarXXX** [spring-projects/spring-session#921]
I am trying to use spring-session where a java object is retrieved from session and some values are update . It works in that particular request but they are not persisted in redis for the next invocation.

I have attached standalone sample project that reproduces the issue. I use an xml configuration since our current project used XML based.

The configuration works for explicit session.setAttribute(someKey, someValue)

The configuration does not work for scenario session.getAttribute(somekey).getSomeObject().setSomeValue("newValue") - Our current code has lot of such coding .

I have the redis flush mode as Immediate in the configuration and have defined a kyro serializer for storing the java objects in redis.

I ve attached a sample project that reproduces the issue.
[spring-session-sample.zip](https://github.com/spring-projects/spring-session/files/1447901/spring-session-sample.zip)

**Comment by shankarXXX** [comment]
The problem is same as issue https://github.com/spring-projects/spring-session/issues/311. I created a new ticket because that one is closed with the solution as the RedisFlushMode

**Comment by shankarXXX** [comment]
I am not sure if this is related to The problem is same as issue https://github.com/spring-projects/spring-session/issues/311 since the solution for that seems to be the IMMEDIATE flush setting which is not working for me

**Comment by shankarXXX** [comment]
@rwinch  Any suggestions to my problem?

**Comment by vpavic** [comment]
@shankarXXX I'm unable to run your sample as the build scripts refers to multiple variables are unavailable. Please make sure the project can be built on its own.

Nevertheless, using something like `session.getAttribute(somekey).getSomeObject().setSomeValue("newValue")` won't work even with `IMMEDIATE` flush mode since there's no invocation on the `HttpSession` that would invoke the underlying implementation backed by Spring Session and therefore allow the changes to be persisted. So using `session.setAttribute(someKey, someValue)` is mandatory.

Bear in mind that Spring Session provides implementation of Servlet API's `HttpSession` that's backed by an external data store. This means that while interacting with `HttpSession` you are in fact interacting with a copy retrieved from the session store - in this case Redis. In contrast, when using Tomcat's default session management the store is _in-memory_, which means you're interacting with the same `HttpSession` instance (rather than a copy) that represents a given session.

**Comment by shankarXXX** [comment]
@vpavic   My bad.. I fixed the project issues  and attached.

To give you a perspective of the problem, I have a monolith app bound to weblogic containers which we are trying to move it cloud(AWS). 

Spring session is a very good choice for us to move out of container bound logic and it falls in line with strategy and timelines to move in AWS direction with spring boot tomcat based applications.

For the first phase, we want to replace httpsession with spring session backed redis so that we can split our apps with httpsession backing and slowly rewrite the session piece of the logic and make it eventually stateless backed fully by redis. All our use cases are met except so far  session.getAttibute(somekey).setSomeValue(someValue) and our code base has lot of such coding.

I am open to suggestions as I am really excited about the possibilities of using spring-session but other than a complete rewrite of all the places we have such coding i see no alternative to our current problem.  

I tried following approach to address the problem  but so far i have unable been to solve this problem

1. extend sessionRepository filter to override and do get and set selected session atrributes to get it to working even though it was a quick and dirty solution but would have still covered our requirements but since all the internals are private and final I am unable to do so. 

2. Implement an aspect on session.getAttributes() method calls in a particular request to to explictly capture all the get attribute events. The problem with this approach is I am unable to determine which object was modified in the session which is believe is the same approach for spring-session which is why it does not get added to the delta from my debugging observations


IMO the documentation can clearly mention the above scenario as it is a not so transparent integration   as quoted from the reference documentation.

Spring Session provides an API and implementations for managing a user’s session informatio**n. It also provides transparent integration with:

HttpSession - allows replacing the HttpSession in an application container (i.e. Tomcat) neutral way. **Additional features include:


[spring-session-sample.zip](https://github.com/spring-projects/spring-session/files/1461769/spring-session-sample.zip)

**Comment by vpavic** [comment]
Thanks for the updated sample app @shankarXXX.

We can certainly consider improving our documentation to make this more obvious and avoid surprises for users (like you) who are migrating from container based in-memory `HttpSession` management.

For the record, here are a few more references (besides #311 you already referenced) to similar issues: #133, #177 and #584.

Important thing to note is that Servlet API's `HttpSession` contract offers no guarantees that changes to objects obtained using `HttpSession#getAttribute` will be tracked, and that you'd run into same situation if using, for instance, Tomcat's clustering/session replication mechanism.

**Comment by shankarXXX** [comment]
@vpavic  thanks for the response .  Though I agree it is an incorrect practice many developers do such kinda coding  either in a hurry or lack of full understanding and I have more than one application which we have lined up for cloud migration that has lot of such coding accumulated over the years 

Is there a plan to support changes to objects using session.getAttribute in future releases of spring-session

**Comment by vpavic** [comment]
> Is there a plan to support changes to objects using session.getAttribute in future releases of spring-session

I'm afraid not. The framework isn't the place for workarounds for improper API usage, and as explained above, the problem isn't specific to Spring Session but also to some other session replication mechanisms.

I do agree we can somewhat improve the docs so that it's clear that `SessionRepository` implementations return the copies of the session and that any changes made to the returned object should be stored back to the repo.
