### ISSUE TITLE
Provides a @EnableInMemoryWebSesssion to take over custom MapReactiveSessionRepository

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-session#924]
In the latest Spring Session 2.0.0.RC1(I am using Spring Boot 2.0.0.M6 as dependency management), all implementation based `@Enable<XXX Implementation>WebSession` has a consistent format and provide default configurations, eg for Redis, Mongo etc, but the `MapReactiveSessionRepository` is an exception.

When I use `MapReactiveSessionRepository` I have to customize  `MapReactiveSessionRepository` myself. 

If possible provide a `@EnableInMemoryWebSesssion` or `@EnableEmbeddedWebSesssion` for the `MapReactiveSessionRepository` by default.

**Comment by vpavic** [comment]
There's no such configuration infrastructure for `MapSessionRepository` either.

Note that both `MapSessionRepository` and `MapReactiveSessionRepository` had their default constructors removed in #866 and #870, respectively. This was done since instances constructed that way were backed by `ConcurrentHashMap` and as such couldn't be considered production-grade since weren't cluster ready and did not take care of purging of expired session, which can lead to memory issues after prolonged use. So we made it a requirement that users provide a `Map` that will back `MapSessionRepository`/`MapReactiveSessionRepository`.

Regarding the configuration infrastructure, from the above it should be obvious that `MapSessionRepository`/`MapReactiveSessionRepository` cannot be configured without user's involvement in configuring the underlying `Map`. However, you can still use `@EnableSpringHttpSession`/`@EnableSpringWebSession` to set up the entire Spring Session infrastructure which leaves it to user only to configure the session repository instance.

**Comment by hantsy** [comment]
@vpavic Ok, thanks for your explanation.
