### ISSUE TITLE
Allow Redis sessions to ignore certain paths when working out whether to refresh the last access time

### ISSUE THREAD

**Issue by chrisburrell** [spring-projects/spring-session#944]
By default, in a vanilla web application, all calls refresh the session. However sometimes a webapp may have a polling mechanism. In this instance, it is useful to be able to tell the session manager to ignore certain updates.

By allowing the developer to configure an expiry condition, this allows more flexibility to the developer to define when a session should expire.

**Comment by vpavic** [comment]
@chrisburrell Are you using Spring Security? If yes, you can create a dedicated security config for path(s) that you don't want to use session, and apply the `SessionCreationPolicy#STATELESS`.

**Comment by chrisburrell** [comment]
Hi vpavic - thanks for the hint - I'll give that a shot.

**Comment by chrisburrell** [comment]
@vpavic I'm not sure this will work for us - as we want to read from the session but not affect the session itself. For example, our backend is changing the roles/permissions associated in the sessions. 

Our front-end polls a URL to pick up any changes. This then results in looking up the session information. And then the redis lastAccessTime field gets updated, which then in turns resets the expiry time of the session. Instead we want to be able to read the session without affecting the last access time.

From the javadoc in SessionCreationPolicy, it sounds like the session won't be available.

**Comment by vpavic** [comment]
@chrisburrell Thanks for following up with more details on your use case.

I'm afraid what you're describing is something we cannot consider supporting. You're expecting to read from the session but at the same time pretend that you haven't touched the session (by not updating the `lastAccessTime`) which is clearly in conflict with the spec and would be somewhat of _cheating_.

As an alternative, maybe you could use an alternative approach for obtaining session so that you're not doing it through standard Servlet API mechanisms but rather directly from Spring Session's `SessionRepository`?

**Comment by vpavic** [comment]
Comparing a data structure like stack to `HttpSession` API isn't quite a suitable comparison IMO.

The behavior we're discussing here is fairly well defined in the `HttpSession` API and what you're requesting is in violation of this API.

> Is there a way of finding out if a user is authenticated without reading the session?

As I tried to explained in my previous comment, you can use the `SessionRepository` directly in order to obtain the session without the involvement of standard `HttpSession` mechanisms. The options are:

- `SessionRepository#findById` (note this is `SessionRepository#getSession` in pre-2.0)
- `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue`

Which option to use really depends on what information you have available in place where you'd like to obtain the session. Hope this provides some alternatives for you.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
