### ISSUE TITLE
The url for spring session on the home page is wrong 

### ISSUE THREAD

**Issue by bpzhang** [spring-projects/spring-session#948]
the right :   https://projects.spring.io/spring-session/

**Comment by vpavic** [comment]
Thanks for the report @bpzhang.

I assume the home page your referring to is project's page at GitHub (https://github.com/spring-projects/spring-session) and the invalid URL is the one in project's description, currently pointing at https://spring.io/spring-session (which returns 404)?

Assigning to @rwinch since I don't have the needed permission to update this.

**Comment by rwinch** [comment]
This is due to sagan's redirects no longer working. I created https://github.com/spring-io/sagan/issues/808

**Comment by rwinch** [comment]
Thanks again for the report. This was fixed in Sagan so I'm closing this as won't fix
