### ISSUE TITLE
Why does spring session store unauthorized request in redis? 

### ISSUE THREAD

**Issue by mrshawn191** [spring-projects/spring-session#950]
Why does spring session store unauthorized request in redis? 

I've noticed when doing curl requests, but not via webbrowser? it saves a row, including information such as client, where the request came from etc.

**Comment by vpavic** [comment]
If an HTTP request triggers the creation of the new session, it will get stored in the underlying session store. This is completely unrelated to authentication concerns - the authentication typically is stored in a session, but Spring Session knows nothing about that since all it actually does is it provides an implementation of Servlet API's `HttpSession`.

When you're using a web browser to initiate requests, the browser takes care of sending the cookie and therefore correlates the request with the existing session. If you're using curl you have to ensure yourself that you're setting the session cookie (or header, if header session strategy is used).

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.

**Comment by mrshawn191** [comment]
Oh ok thank you for the explanation makes is much clearer now thanks.
