### ISSUE TITLE
How to use spring-session and spring-security-oauth2 in an either/or relationship in securing a resource

### ISSUE THREAD

**Issue by aankur** [spring-projects/spring-session#972]
Hi, 
i have a requirement to add Oauth to an existing implementation that uses spring-session and uses @EnableRedisHttpSession to enable sessions.
This might be related to #149 , but i am not sure.

Suppose i have a protected controller at **/api/v1/test** i want to use **either** of the authentication mechanism to access the endpoint , By that i mean that a web authenticated consumer of the API or OAuth authenticated consumer  both should be able to access the endpoint.

The problem here is that both the implementation don't allow each other to work. we are able to use only one of the implementation at any given time.

If security.oauth2.resource.filter-order=2 is set WebSecurityConfigurerAdapter _order_(3) is specified only Oauth works.

If security.oauth2.resource.filter-order=3 is set WebSecurityConfigurerAdapter _order_(2) is specified only http session via cookie works.

I am unable to make them both work. so i have created a sample micro-service app that displays this behavior. this behavior is  is also reproducible on the single auth service also.
the repository hosting the build is  at [https://github.com/aankur/spring-authentication-session-oauth2](url)

Help Appreciated
aankur/spring-authentication-session-oauth2#2

**Comment by aankur** [comment]
i have only been able to do the authentication by separating the endpoints,
i have divided the endpoints into /web/** and /api/**
it can be referenced in aankur/spring-authentication-session-oauth2#3

is this the only way to do so,

**Comment by aankur** [comment]
i was able to solve this through by using http.requestMatcher as suggested here https://stackoverflow.com/questions/48328062/how-to-protect-the-same-resource-using-both-spring-session-and-spring-security-o

**Comment by aankur** [comment]
i had one more thing to add is this the correct way to do it. i have been suggested to that this is a hacky solution.

**Comment by eleftherias** [comment]
Thanks for reaching out @aankur.
I don't believe this is a Spring Session question, since the same logic would apply even if you were not using Spring Session.
As you mentioned there are way to work around this, including the suggestion that you shared, as well as creating a custom `AuthenticationProvider`.
I would advise you to consider your application architecture and whether it's necessary to have users authenticating in multiple ways, or whether this can be solved using something standardized, like OAuth 2.0 with multiple authorization servers.
