### ISSUE TITLE
Spring-Session + Redisson + Sentinel are compatible ?

### ISSUE THREAD

**Issue by DevWantJustHaveFun** [spring-projects/spring-session#990]
Everything is in the title :) 
I'm asking because I'm experiencing strange issues with this configuration and I see nothing about redisson in your documentation

More detail here => https://github.com/redisson/redisson/issues/1272

I'm using SpringBoot 1.5.8.RELEASE
Redisson 3.5.4
Spring Session 1.3.1.RELEASE

**Comment by vpavic** [comment]
Thanks for the report @DevWantJustHaveFun.

Looking at the referenced issue, you're using `@EnableRedissonHttpSession` which isn't a part of Spring Session project but is rather a 3rd party extension module. I'd suggest to report an issue with maintainers of that extension.

If it turns out to be a problem with Spring Session Core we can always re-open the issue.
